/* Vietnamese beginner vocabulary — two levels (A1 ≈ basics, A2 ≈ everyday life).
 * Northern (Hanoi) standard. `pr` is a rough pronunciation respelling for English speakers.
 * Fields: id, w (word), pr (pronunciation), en, cat, lvl, ex (example), exEn
 */
window.VI_WORDS = [
  // ---------- A1: greetings & phrases ----------
  { id: "v1",  w: "xin chào",      pr: "sin chow",          en: "hello",                        cat: "phrases",   lvl: 1, ex: "Xin chào, tôi là Nam.", exEn: "Hello, I am Nam." },
  { id: "v2",  w: "cảm ơn",        pr: "kahm uhn",          en: "thank you",                    cat: "phrases",   lvl: 1, ex: "Cảm ơn bạn nhiều.", exEn: "Thank you very much." },
  { id: "v3",  w: "xin lỗi",       pr: "sin loy",           en: "sorry, excuse me",             cat: "phrases",   lvl: 1, ex: "Xin lỗi, tôi đến muộn.", exEn: "Sorry, I'm late." },
  { id: "v4",  w: "tạm biệt",      pr: "tahm byet",         en: "goodbye",                      cat: "phrases",   lvl: 1, ex: "Tạm biệt, hẹn gặp lại!", exEn: "Goodbye, see you again!" },
  { id: "v5",  w: "không có gì",   pr: "khohng koh zee",    en: "you're welcome; it's nothing", cat: "phrases",   lvl: 1, ex: "Cảm ơn! — Không có gì.", exEn: "Thanks! — You're welcome." },
  { id: "v6",  w: "vâng",          pr: "vuhng",             en: "yes (polite)",                 cat: "phrases",   lvl: 1, ex: "Vâng, tôi hiểu.", exEn: "Yes, I understand." },
  { id: "v7",  w: "không",         pr: "khohng",            en: "no; not",                      cat: "particles", lvl: 1, ex: "Tôi không biết.", exEn: "I don't know." },
  { id: "v8",  w: "làm ơn",        pr: "lahm uhn",          en: "please",                       cat: "phrases",   lvl: 1, ex: "Làm ơn nói chậm hơn.", exEn: "Please speak more slowly." },
  { id: "v9",  w: "hẹn gặp lại",   pr: "hen gap lai",       en: "see you again",                cat: "phrases",   lvl: 1, ex: "Hẹn gặp lại ngày mai!", exEn: "See you tomorrow!" },
  { id: "v10", w: "rất vui được gặp bạn", pr: "zuht vooy duhk gap ban", en: "nice to meet you", cat: "phrases",   lvl: 1, ex: "Rất vui được gặp bạn!", exEn: "Nice to meet you!" },
  // ---------- A1: pronouns ----------
  { id: "v11", w: "tôi",           pr: "toy",               en: "I, me",                        cat: "pronouns",  lvl: 1, ex: "Tôi là sinh viên.", exEn: "I am a student." },
  { id: "v12", w: "bạn",           pr: "ban",               en: "you (friend, same age)",       cat: "pronouns",  lvl: 1, ex: "Bạn tên là gì?", exEn: "What is your name?" },
  { id: "v13", w: "anh",           pr: "ang",               en: "you/he (older male); older brother", cat: "pronouns", lvl: 1, ex: "Anh là người Việt à?", exEn: "Are you Vietnamese?" },
  { id: "v14", w: "chị",           pr: "chee",              en: "you/she (older female); older sister", cat: "pronouns", lvl: 1, ex: "Chị đi đâu?", exEn: "Where are you going?" },
  { id: "v15", w: "em",            pr: "em",                en: "you/I (younger person)",       cat: "pronouns",  lvl: 1, ex: "Em học tiếng Việt.", exEn: "I (younger) study Vietnamese." },
  { id: "v16", w: "chúng tôi",     pr: "choong toy",        en: "we (excluding listener)",      cat: "pronouns",  lvl: 1, ex: "Chúng tôi là bạn.", exEn: "We are friends." },
  { id: "v17", w: "họ",            pr: "haw",               en: "they",                         cat: "pronouns",  lvl: 1, ex: "Họ sống ở Hà Nội.", exEn: "They live in Hanoi." },
  { id: "v18", w: "ông",           pr: "ohng",              en: "grandfather; Mr. (older man)", cat: "pronouns",  lvl: 1, ex: "Ông ấy là bác sĩ.", exEn: "He (older man) is a doctor." },
  { id: "v19", w: "bà",            pr: "bah",               en: "grandmother; Mrs. (older woman)", cat: "pronouns", lvl: 1, ex: "Bà ấy rất tốt.", exEn: "She (older woman) is very kind." },
  { id: "v20", w: "này",           pr: "nai",               en: "this",                         cat: "pronouns",  lvl: 1, ex: "Cái này là gì?", exEn: "What is this?" },
  { id: "v21", w: "đó",            pr: "doh",               en: "that",                         cat: "pronouns",  lvl: 1, ex: "Cái đó rất đẹp.", exEn: "That one is very beautiful." },
  // ---------- A1: question words ----------
  { id: "v22", w: "gì",            pr: "zee",               en: "what",                         cat: "question",  lvl: 1, ex: "Đây là gì?", exEn: "What is this?" },
  { id: "v23", w: "ai",            pr: "ai",                en: "who",                          cat: "question",  lvl: 1, ex: "Ai đó?", exEn: "Who is that?" },
  { id: "v24", w: "ở đâu",         pr: "uh dow",            en: "where",                        cat: "question",  lvl: 1, ex: "Nhà vệ sinh ở đâu?", exEn: "Where is the restroom?" },
  { id: "v25", w: "khi nào",       pr: "khee now",          en: "when",                         cat: "question",  lvl: 1, ex: "Khi nào bạn đi?", exEn: "When are you leaving?" },
  { id: "v26", w: "tại sao",       pr: "tai sow",           en: "why",                          cat: "question",  lvl: 1, ex: "Tại sao bạn học tiếng Việt?", exEn: "Why do you study Vietnamese?" },
  { id: "v27", w: "bao nhiêu",     pr: "bow nyew",          en: "how much, how many",           cat: "question",  lvl: 1, ex: "Cái này bao nhiêu tiền?", exEn: "How much is this?" },
  { id: "v28", w: "thế nào",       pr: "teh now",           en: "how",                          cat: "question",  lvl: 1, ex: "Bạn thế nào?", exEn: "How are you?" },
  { id: "v29", w: "nào",           pr: "now",               en: "which",                        cat: "question",  lvl: 1, ex: "Bạn thích cái nào?", exEn: "Which one do you like?" },
  // ---------- A1: numbers ----------
  { id: "v30", w: "một",           pr: "moht",              en: "one",                          cat: "numbers",   lvl: 1, ex: "Tôi có một con mèo.", exEn: "I have one cat." },
  { id: "v31", w: "hai",           pr: "hai",               en: "two",                          cat: "numbers",   lvl: 1, ex: "Hai cốc cà phê.", exEn: "Two cups of coffee." },
  { id: "v32", w: "ba",            pr: "bah",               en: "three; dad",                   cat: "numbers",   lvl: 1, ex: "Tôi có ba anh em.", exEn: "I have three siblings." },
  { id: "v33", w: "bốn",           pr: "bohn",              en: "four",                         cat: "numbers",   lvl: 1, ex: "Bốn giờ chiều.", exEn: "Four o'clock in the afternoon." },
  { id: "v34", w: "năm",           pr: "nam",               en: "five; year",                   cat: "numbers",   lvl: 1, ex: "Năm người.", exEn: "Five people." },
  { id: "v35", w: "sáu",           pr: "sow",               en: "six",                          cat: "numbers",   lvl: 1, ex: "Sáu giờ sáng.", exEn: "Six in the morning." },
  { id: "v36", w: "bảy",           pr: "bay",               en: "seven",                        cat: "numbers",   lvl: 1, ex: "Một tuần có bảy ngày.", exEn: "A week has seven days." },
  { id: "v37", w: "tám",           pr: "tahm",              en: "eight",                        cat: "numbers",   lvl: 1, ex: "Tám quyển sách.", exEn: "Eight books." },
  { id: "v38", w: "chín",          pr: "cheen",             en: "nine",                         cat: "numbers",   lvl: 1, ex: "Chín giờ tối.", exEn: "Nine in the evening." },
  { id: "v39", w: "mười",          pr: "muh-ee",            en: "ten",                          cat: "numbers",   lvl: 1, ex: "Mười nghìn đồng.", exEn: "Ten thousand dong." },
  { id: "v40", w: "trăm",          pr: "chahm",             en: "hundred",                      cat: "numbers",   lvl: 1, ex: "Một trăm nghìn.", exEn: "One hundred thousand." },
  { id: "v41", w: "nghìn",         pr: "ngeen",             en: "thousand",                     cat: "numbers",   lvl: 1, ex: "Hai mươi nghìn đồng.", exEn: "Twenty thousand dong." },
  // ---------- A1: people & family ----------
  { id: "v42", w: "người",         pr: "nguh-ee",           en: "person, people",               cat: "people",    lvl: 1, ex: "Tôi là người Đức.", exEn: "I am German." },
  { id: "v43", w: "bố",            pr: "boh",               en: "father (North)",               cat: "family",    lvl: 1, ex: "Bố tôi là giáo viên.", exEn: "My father is a teacher." },
  { id: "v44", w: "mẹ",            pr: "meh",               en: "mother",                       cat: "family",    lvl: 1, ex: "Mẹ tôi nấu ăn rất ngon.", exEn: "My mother cooks very well." },
  { id: "v45", w: "con",           pr: "kon",               en: "child (of parents); classifier for animals", cat: "family", lvl: 1, ex: "Họ có hai con.", exEn: "They have two children." },
  { id: "v46", w: "gia đình",      pr: "zah ding",          en: "family",                       cat: "family",    lvl: 1, ex: "Gia đình tôi có bốn người.", exEn: "My family has four people." },
  { id: "v47", w: "bạn bè",        pr: "ban beh",           en: "friends",                      cat: "people",    lvl: 1, ex: "Tôi đi chơi với bạn bè.", exEn: "I go out with friends." },
  { id: "v48", w: "tên",           pr: "ten",               en: "name",                         cat: "people",    lvl: 1, ex: "Tên tôi là Linh.", exEn: "My name is Linh." },
  { id: "v49", w: "giáo viên",     pr: "zow vyen",          en: "teacher",                      cat: "people",    lvl: 1, ex: "Cô ấy là giáo viên.", exEn: "She is a teacher." },
  { id: "v50", w: "sinh viên",     pr: "sing vyen",         en: "university student",           cat: "people",    lvl: 1, ex: "Tôi là sinh viên.", exEn: "I am a student." },
  { id: "v51", w: "bác sĩ",        pr: "bahk see",          en: "doctor",                       cat: "people",    lvl: 1, ex: "Anh ấy là bác sĩ.", exEn: "He is a doctor." },
  { id: "v52", w: "chồng",         pr: "chohng",            en: "husband",                      cat: "family",    lvl: 1, ex: "Chồng tôi là kỹ sư.", exEn: "My husband is an engineer." },
  { id: "v53", w: "vợ",            pr: "vuh",               en: "wife",                         cat: "family",    lvl: 1, ex: "Vợ tôi tên là Hoa.", exEn: "My wife's name is Hoa." },
  // ---------- A1: verbs ----------
  { id: "v54", w: "là",            pr: "lah",               en: "to be (am, is, are)",          cat: "verbs",     lvl: 1, ex: "Tôi là người Việt Nam.", exEn: "I am Vietnamese." },
  { id: "v55", w: "có",            pr: "koh",               en: "to have; there is",            cat: "verbs",     lvl: 1, ex: "Tôi có một câu hỏi.", exEn: "I have a question." },
  { id: "v56", w: "đi",            pr: "dee",               en: "to go",                        cat: "verbs",     lvl: 1, ex: "Tôi đi làm.", exEn: "I go to work." },
  { id: "v57", w: "đến",           pr: "den",               en: "to come, to arrive",           cat: "verbs",     lvl: 1, ex: "Bạn đến từ đâu?", exEn: "Where do you come from?" },
  { id: "v58", w: "ăn",            pr: "an",                en: "to eat",                       cat: "verbs",     lvl: 1, ex: "Bạn muốn ăn gì?", exEn: "What do you want to eat?" },
  { id: "v59", w: "uống",          pr: "oo-uhng",           en: "to drink",                     cat: "verbs",     lvl: 1, ex: "Tôi uống cà phê mỗi sáng.", exEn: "I drink coffee every morning." },
  { id: "v60", w: "nói",           pr: "noy",               en: "to speak, to say",             cat: "verbs",     lvl: 1, ex: "Bạn nói tiếng Anh không?", exEn: "Do you speak English?" },
  { id: "v61", w: "học",           pr: "hawp",              en: "to study, to learn",           cat: "verbs",     lvl: 1, ex: "Tôi học tiếng Việt.", exEn: "I study Vietnamese." },
  { id: "v62", w: "làm",           pr: "lahm",              en: "to do, to make, to work",      cat: "verbs",     lvl: 1, ex: "Bạn làm gì?", exEn: "What do you do?" },
  { id: "v63", w: "thích",         pr: "tick",              en: "to like",                      cat: "verbs",     lvl: 1, ex: "Tôi thích phở.", exEn: "I like pho." },
  { id: "v64", w: "muốn",          pr: "moo-uhn",           en: "to want",                      cat: "verbs",     lvl: 1, ex: "Tôi muốn đi Việt Nam.", exEn: "I want to go to Vietnam." },
  { id: "v65", w: "biết",          pr: "byet",              en: "to know",                      cat: "verbs",     lvl: 1, ex: "Tôi không biết.", exEn: "I don't know." },
  { id: "v66", w: "hiểu",          pr: "hyew",              en: "to understand",                cat: "verbs",     lvl: 1, ex: "Tôi hiểu rồi.", exEn: "I understand now." },
  { id: "v67", w: "xem",           pr: "sem",               en: "to watch, to look at",         cat: "verbs",     lvl: 1, ex: "Tôi xem phim.", exEn: "I watch a movie." },
  { id: "v68", w: "nghe",          pr: "ngeh",              en: "to listen, to hear",           cat: "verbs",     lvl: 1, ex: "Tôi nghe nhạc.", exEn: "I listen to music." },
  { id: "v69", w: "đọc",           pr: "dawp",              en: "to read",                      cat: "verbs",     lvl: 1, ex: "Tôi đọc sách.", exEn: "I read a book." },
  { id: "v70", w: "viết",          pr: "vyet",              en: "to write",                     cat: "verbs",     lvl: 1, ex: "Viết tên của bạn.", exEn: "Write your name." },
  { id: "v71", w: "mua",           pr: "moo-ah",            en: "to buy",                       cat: "verbs",     lvl: 1, ex: "Tôi muốn mua cái này.", exEn: "I want to buy this." },
  { id: "v72", w: "bán",           pr: "bahn",              en: "to sell",                      cat: "verbs",     lvl: 1, ex: "Ở đây bán hoa quả.", exEn: "Fruit is sold here." },
  { id: "v73", w: "ngủ",           pr: "ngoo",              en: "to sleep",                     cat: "verbs",     lvl: 1, ex: "Tôi đi ngủ lúc mười giờ.", exEn: "I go to sleep at ten." },
  { id: "v74", w: "sống",          pr: "sohng",             en: "to live",                      cat: "verbs",     lvl: 1, ex: "Bạn sống ở đâu?", exEn: "Where do you live?" },
  { id: "v75", w: "gặp",           pr: "gap",               en: "to meet",                      cat: "verbs",     lvl: 1, ex: "Rất vui được gặp bạn.", exEn: "Nice to meet you." },
  { id: "v76", w: "yêu",           pr: "yew",               en: "to love",                      cat: "verbs",     lvl: 1, ex: "Tôi yêu bạn.", exEn: "I love you." },
  { id: "v77", w: "cần",           pr: "kuhn",              en: "to need",                      cat: "verbs",     lvl: 1, ex: "Tôi cần giúp đỡ.", exEn: "I need help." },
  { id: "v78", w: "có thể",        pr: "koh teh",           en: "can, to be able to",           cat: "verbs",     lvl: 1, ex: "Bạn có thể giúp tôi không?", exEn: "Can you help me?" },
  { id: "v79", w: "ngồi",          pr: "ngoy",              en: "to sit",                       cat: "verbs",     lvl: 1, ex: "Mời ngồi.", exEn: "Please sit down." },
  { id: "v80", w: "mở",            pr: "muh",               en: "to open",                      cat: "verbs",     lvl: 1, ex: "Mở cửa ra.", exEn: "Open the door." },
  { id: "v81", w: "đóng",          pr: "dohng",             en: "to close",                     cat: "verbs",     lvl: 1, ex: "Đóng cửa lại.", exEn: "Close the door." },
  { id: "v82", w: "về",            pr: "veh",               en: "to return, to go back",        cat: "verbs",     lvl: 1, ex: "Tôi về nhà.", exEn: "I go home." },
  { id: "v83", w: "chờ",           pr: "chuh",              en: "to wait",                      cat: "verbs",     lvl: 1, ex: "Chờ một chút.", exEn: "Wait a moment." },
  { id: "v84", w: "gọi",           pr: "goy",               en: "to call; to order (food)",     cat: "verbs",     lvl: 1, ex: "Tôi gọi một bát phở.", exEn: "I order a bowl of pho." },
  { id: "v85", w: "giúp",          pr: "zoop",              en: "to help",                      cat: "verbs",     lvl: 1, ex: "Bạn giúp tôi được không?", exEn: "Could you help me?" },
  // ---------- A1: food & drink ----------
  { id: "v86", w: "cơm",           pr: "kuhm",              en: "cooked rice; meal",            cat: "food",      lvl: 1, ex: "Tôi ăn cơm với gia đình.", exEn: "I have a meal with my family." },
  { id: "v87", w: "phở",           pr: "fuh",               en: "pho (noodle soup)",            cat: "food",      lvl: 1, ex: "Phở bò rất ngon.", exEn: "Beef pho is delicious." },
  { id: "v88", w: "nước",          pr: "nuh-uhk",           en: "water; country",               cat: "food",      lvl: 1, ex: "Cho tôi một chai nước.", exEn: "Give me a bottle of water." },
  { id: "v89", w: "cà phê",        pr: "kah feh",           en: "coffee",                       cat: "food",      lvl: 1, ex: "Cà phê sữa đá.", exEn: "Iced milk coffee." },
  { id: "v90", w: "trà",           pr: "chah",              en: "tea",                          cat: "food",      lvl: 1, ex: "Mời bạn uống trà.", exEn: "Please have some tea." },
  { id: "v91", w: "bia",           pr: "bee-ah",            en: "beer",                         cat: "food",      lvl: 1, ex: "Hai chai bia.", exEn: "Two bottles of beer." },
  { id: "v92", w: "bánh mì",       pr: "bang mee",          en: "bread; banh mi sandwich",      cat: "food",      lvl: 1, ex: "Một bánh mì thịt.", exEn: "One banh mi with meat." },
  { id: "v93", w: "thịt",          pr: "tit",               en: "meat",                         cat: "food",      lvl: 1, ex: "Tôi không ăn thịt.", exEn: "I don't eat meat." },
  { id: "v94", w: "cá",            pr: "kah",               en: "fish",                         cat: "food",      lvl: 1, ex: "Cá này tươi không?", exEn: "Is this fish fresh?" },
  { id: "v95", w: "rau",           pr: "zow",               en: "vegetables",                   cat: "food",      lvl: 1, ex: "Ăn nhiều rau tốt cho sức khỏe.", exEn: "Eating lots of vegetables is healthy." },
  { id: "v96", w: "hoa quả",       pr: "hwah kwah",         en: "fruit",                        cat: "food",      lvl: 1, ex: "Tôi thích ăn hoa quả.", exEn: "I like eating fruit." },
  { id: "v97", w: "trứng",         pr: "chuhng",            en: "egg",                          cat: "food",      lvl: 1, ex: "Hai quả trứng.", exEn: "Two eggs." },
  { id: "v98", w: "sữa",           pr: "suh-ah",            en: "milk",                         cat: "food",      lvl: 1, ex: "Cà phê sữa.", exEn: "Coffee with milk." },
  { id: "v99", w: "ngon",          pr: "ngon",              en: "delicious",                    cat: "adjectives", lvl: 1, ex: "Món này rất ngon!", exEn: "This dish is delicious!" },
  { id: "v100", w: "đói",          pr: "doy",               en: "hungry",                       cat: "adjectives", lvl: 1, ex: "Tôi đói rồi.", exEn: "I'm hungry." },
  // ---------- A1: places ----------
  { id: "v101", w: "nhà",          pr: "nyah",              en: "house, home",                  cat: "places",    lvl: 1, ex: "Nhà tôi ở Hà Nội.", exEn: "My home is in Hanoi." },
  { id: "v102", w: "Việt Nam",     pr: "vyet nahm",         en: "Vietnam",                      cat: "places",    lvl: 1, ex: "Tôi yêu Việt Nam.", exEn: "I love Vietnam." },
  { id: "v103", w: "Hà Nội",       pr: "hah noy",           en: "Hanoi",                        cat: "places",    lvl: 1, ex: "Hà Nội là thủ đô.", exEn: "Hanoi is the capital." },
  { id: "v104", w: "trường",       pr: "chuh-uhng",         en: "school",                       cat: "places",    lvl: 1, ex: "Trường ở gần đây.", exEn: "The school is near here." },
  { id: "v105", w: "chợ",          pr: "chuh",              en: "market",                       cat: "places",    lvl: 1, ex: "Mẹ đi chợ.", exEn: "Mom goes to the market." },
  { id: "v106", w: "cửa hàng",     pr: "kuh-ah hahng",      en: "shop, store",                  cat: "places",    lvl: 1, ex: "Cửa hàng mở lúc tám giờ.", exEn: "The shop opens at eight." },
  { id: "v107", w: "nhà hàng",     pr: "nyah hahng",        en: "restaurant",                   cat: "places",    lvl: 1, ex: "Nhà hàng này rất ngon.", exEn: "This restaurant is very good." },
  { id: "v108", w: "khách sạn",    pr: "khack sahn",        en: "hotel",                        cat: "places",    lvl: 1, ex: "Tôi ở khách sạn.", exEn: "I'm staying at a hotel." },
  { id: "v109", w: "bệnh viện",    pr: "beng vyen",         en: "hospital",                     cat: "places",    lvl: 1, ex: "Bệnh viện ở đâu?", exEn: "Where is the hospital?" },
  { id: "v110", w: "sân bay",      pr: "suhn bai",          en: "airport",                      cat: "places",    lvl: 1, ex: "Tôi đi sân bay.", exEn: "I'm going to the airport." },
  { id: "v111", w: "đường",        pr: "duh-uhng",          en: "street, road; sugar",          cat: "places",    lvl: 1, ex: "Đường này rất đông.", exEn: "This street is very crowded." },
  { id: "v112", w: "ở",            pr: "uh",                en: "at, in; to live at",           cat: "particles", lvl: 1, ex: "Tôi ở Hà Nội.", exEn: "I live in Hanoi." },
  { id: "v113", w: "đây",          pr: "day",               en: "here",                         cat: "places",    lvl: 1, ex: "Đây là nhà tôi.", exEn: "This is my house." },
  { id: "v114", w: "kia",          pr: "kee-ah",            en: "over there",                   cat: "places",    lvl: 1, ex: "Cái kia bao nhiêu?", exEn: "How much is that one over there?" },
  // ---------- A1: time ----------
  { id: "v115", w: "hôm nay",      pr: "hohm nai",          en: "today",                        cat: "time",      lvl: 1, ex: "Hôm nay trời đẹp.", exEn: "The weather is nice today." },
  { id: "v116", w: "ngày mai",     pr: "ngai mai",          en: "tomorrow",                     cat: "time",      lvl: 1, ex: "Ngày mai tôi đi làm.", exEn: "Tomorrow I go to work." },
  { id: "v117", w: "hôm qua",      pr: "hohm kwah",         en: "yesterday",                    cat: "time",      lvl: 1, ex: "Hôm qua tôi ở nhà.", exEn: "Yesterday I stayed home." },
  { id: "v118", w: "bây giờ",      pr: "bay zuh",           en: "now",                          cat: "time",      lvl: 1, ex: "Bây giờ là mấy giờ?", exEn: "What time is it now?" },
  { id: "v119", w: "giờ",          pr: "zuh",               en: "hour; o'clock",                cat: "time",      lvl: 1, ex: "Bảy giờ sáng.", exEn: "Seven in the morning." },
  { id: "v120", w: "phút",         pr: "foot",              en: "minute",                       cat: "time",      lvl: 1, ex: "Chờ năm phút.", exEn: "Wait five minutes." },
  { id: "v121", w: "ngày",         pr: "ngai",              en: "day",                          cat: "time",      lvl: 1, ex: "Một ngày đẹp.", exEn: "A beautiful day." },
  { id: "v122", w: "tuần",         pr: "too-uhn",           en: "week",                         cat: "time",      lvl: 1, ex: "Tuần sau tôi bận.", exEn: "Next week I'm busy." },
  { id: "v123", w: "tháng",        pr: "tahng",             en: "month",                        cat: "time",      lvl: 1, ex: "Tháng này rất nóng.", exEn: "This month is very hot." },
  { id: "v124", w: "sáng",         pr: "sahng",             en: "morning",                      cat: "time",      lvl: 1, ex: "Chào buổi sáng!", exEn: "Good morning!" },
  { id: "v125", w: "chiều",        pr: "chyew",             en: "afternoon",                    cat: "time",      lvl: 1, ex: "Chiều nay tôi rảnh.", exEn: "I'm free this afternoon." },
  { id: "v126", w: "tối",          pr: "toy",               en: "evening",                      cat: "time",      lvl: 1, ex: "Tối nay ăn gì?", exEn: "What's for dinner tonight?" },
  // ---------- A1: adjectives ----------
  { id: "v127", w: "tốt",          pr: "toht",              en: "good",                         cat: "adjectives", lvl: 1, ex: "Anh ấy là người tốt.", exEn: "He is a good person." },
  { id: "v128", w: "đẹp",          pr: "dep",               en: "beautiful",                    cat: "adjectives", lvl: 1, ex: "Cô ấy rất đẹp.", exEn: "She is very beautiful." },
  { id: "v129", w: "to",           pr: "toh",               en: "big",                          cat: "adjectives", lvl: 1, ex: "Nhà này rất to.", exEn: "This house is very big." },
  { id: "v130", w: "nhỏ",          pr: "nyaw",              en: "small",                        cat: "adjectives", lvl: 1, ex: "Con mèo nhỏ.", exEn: "The small cat." },
  { id: "v131", w: "nóng",         pr: "nohng",             en: "hot",                          cat: "adjectives", lvl: 1, ex: "Hôm nay rất nóng.", exEn: "Today is very hot." },
  { id: "v132", w: "lạnh",         pr: "lang",              en: "cold",                         cat: "adjectives", lvl: 1, ex: "Nước này lạnh.", exEn: "This water is cold." },
  { id: "v133", w: "mới",          pr: "muh-ee",            en: "new",                          cat: "adjectives", lvl: 1, ex: "Xe mới của tôi.", exEn: "My new bike." },
  { id: "v134", w: "cũ",           pr: "koo",               en: "old (things)",                 cat: "adjectives", lvl: 1, ex: "Sách cũ.", exEn: "An old book." },
  { id: "v135", w: "rẻ",           pr: "zeh",               en: "cheap",                        cat: "adjectives", lvl: 1, ex: "Cái này rất rẻ.", exEn: "This is very cheap." },
  { id: "v136", w: "đắt",          pr: "dat",               en: "expensive",                    cat: "adjectives", lvl: 1, ex: "Đắt quá!", exEn: "Too expensive!" },
  { id: "v137", w: "vui",          pr: "vooy",              en: "happy, fun",                   cat: "adjectives", lvl: 1, ex: "Tôi rất vui.", exEn: "I'm very happy." },
  { id: "v138", w: "mệt",          pr: "met",               en: "tired",                        cat: "adjectives", lvl: 1, ex: "Tôi mệt quá.", exEn: "I'm so tired." },
  { id: "v139", w: "bận",          pr: "buhn",              en: "busy",                         cat: "adjectives", lvl: 1, ex: "Hôm nay tôi bận.", exEn: "I'm busy today." },
  { id: "v140", w: "dễ",           pr: "zeh",               en: "easy",                         cat: "adjectives", lvl: 1, ex: "Bài này dễ.", exEn: "This exercise is easy." },
  { id: "v141", w: "khó",          pr: "khoh",              en: "difficult",                    cat: "adjectives", lvl: 1, ex: "Tiếng Việt khó không?", exEn: "Is Vietnamese difficult?" },
  // ---------- A1: particles & adverbs ----------
  { id: "v142", w: "rất",          pr: "zuht",              en: "very",                         cat: "adverbs",   lvl: 1, ex: "Rất tốt!", exEn: "Very good!" },
  { id: "v143", w: "quá",          pr: "kwah",              en: "too, so (after adjective)",    cat: "adverbs",   lvl: 1, ex: "Đẹp quá!", exEn: "So beautiful!" },
  { id: "v144", w: "và",           pr: "vah",               en: "and",                          cat: "particles", lvl: 1, ex: "Tôi và bạn.", exEn: "You and I." },
  { id: "v145", w: "với",          pr: "vuh-ee",            en: "with",                         cat: "particles", lvl: 1, ex: "Đi với tôi.", exEn: "Come with me." },
  { id: "v146", w: "của",          pr: "koo-ah",            en: "of, belonging to",             cat: "particles", lvl: 1, ex: "Sách của tôi.", exEn: "My book." },
  { id: "v147", w: "cũng",         pr: "koong",             en: "also, too",                    cat: "adverbs",   lvl: 1, ex: "Tôi cũng thích.", exEn: "I like it too." },
  { id: "v148", w: "rồi",          pr: "zoy",               en: "already (completed)",          cat: "particles", lvl: 1, ex: "Tôi ăn rồi.", exEn: "I have already eaten." },
  { id: "v149", w: "sẽ",           pr: "seh",               en: "will (future)",                cat: "particles", lvl: 1, ex: "Tôi sẽ đi.", exEn: "I will go." },
  { id: "v150", w: "đang",         pr: "dahng",             en: "-ing (ongoing)",               cat: "particles", lvl: 1, ex: "Tôi đang học.", exEn: "I am studying." },
  { id: "v151", w: "đã",           pr: "dah",               en: "(past marker)",                cat: "particles", lvl: 1, ex: "Tôi đã đến Huế.", exEn: "I have been to Hue." },
  { id: "v152", w: "nhiều",        pr: "nyew",              en: "many, much",                   cat: "adjectives", lvl: 1, ex: "Nhiều người.", exEn: "Many people." },
  { id: "v153", w: "ít",           pr: "eet",               en: "few, little",                  cat: "adjectives", lvl: 1, ex: "Ít tiền.", exEn: "Little money." },
  { id: "v154", w: "tiền",         pr: "tyen",              en: "money",                        cat: "objects",   lvl: 1, ex: "Tôi không có tiền.", exEn: "I have no money." },
  { id: "v155", w: "cái",          pr: "kai",               en: "(classifier for objects)",     cat: "measure",   lvl: 1, ex: "Hai cái ghế.", exEn: "Two chairs." },
  { id: "v156", w: "tiếng Việt",   pr: "tyeng vyet",        en: "Vietnamese language",          cat: "study",     lvl: 1, ex: "Tôi học tiếng Việt.", exEn: "I study Vietnamese." },
  { id: "v157", w: "tiếng Anh",    pr: "tyeng ang",         en: "English language",             cat: "study",     lvl: 1, ex: "Bạn nói tiếng Anh không?", exEn: "Do you speak English?" },
  { id: "v158", w: "sách",         pr: "sack",              en: "book",                         cat: "objects",   lvl: 1, ex: "Tôi đọc sách.", exEn: "I read a book." },
  { id: "v159", w: "xe máy",       pr: "seh mai",           en: "motorbike",                    cat: "transport", lvl: 1, ex: "Tôi đi xe máy.", exEn: "I ride a motorbike." },
  { id: "v160", w: "xe",           pr: "seh",               en: "vehicle, car",                 cat: "transport", lvl: 1, ex: "Xe của bạn ở đâu?", exEn: "Where is your car?" },

  // ---------- A2: family & people ----------
  { id: "v161", w: "anh trai",     pr: "ang chai",          en: "older brother",                cat: "family",    lvl: 2, ex: "Anh trai tôi 30 tuổi.", exEn: "My older brother is 30." },
  { id: "v162", w: "chị gái",      pr: "chee gai",          en: "older sister",                 cat: "family",    lvl: 2, ex: "Chị gái tôi là bác sĩ.", exEn: "My older sister is a doctor." },
  { id: "v163", w: "em trai",      pr: "em chai",           en: "younger brother",              cat: "family",    lvl: 2, ex: "Em trai tôi học đại học.", exEn: "My younger brother is at university." },
  { id: "v164", w: "em gái",       pr: "em gai",            en: "younger sister",               cat: "family",    lvl: 2, ex: "Em gái tôi rất dễ thương.", exEn: "My younger sister is very cute." },
  { id: "v165", w: "con trai",     pr: "kon chai",          en: "son; boy",                     cat: "family",    lvl: 2, ex: "Con trai tôi năm tuổi.", exEn: "My son is five." },
  { id: "v166", w: "con gái",      pr: "kon gai",           en: "daughter; girl",               cat: "family",    lvl: 2, ex: "Con gái tôi thích vẽ.", exEn: "My daughter likes drawing." },
  { id: "v167", w: "cô",           pr: "koh",               en: "aunt; Miss; female teacher",   cat: "family",    lvl: 2, ex: "Cô giáo rất tốt.", exEn: "The (female) teacher is very kind." },
  { id: "v168", w: "chú",          pr: "choo",              en: "uncle (father's younger brother)", cat: "family", lvl: 2, ex: "Chú tôi sống ở Sài Gòn.", exEn: "My uncle lives in Saigon." },
  { id: "v169", w: "đồng nghiệp",  pr: "dohng ngyep",       en: "colleague",                    cat: "people",    lvl: 2, ex: "Đồng nghiệp của tôi rất thân thiện.", exEn: "My colleagues are very friendly." },
  { id: "v170", w: "hàng xóm",     pr: "hahng sohm",        en: "neighbor",                     cat: "people",    lvl: 2, ex: "Hàng xóm của tôi rất tốt.", exEn: "My neighbors are very nice." },
  { id: "v171", w: "khách",        pr: "khack",             en: "guest, customer",              cat: "people",    lvl: 2, ex: "Hôm nay có khách đến.", exEn: "Guests are coming today." },
  { id: "v172", w: "tuổi",         pr: "too-oy",            en: "age, years old",               cat: "people",    lvl: 2, ex: "Bạn bao nhiêu tuổi?", exEn: "How old are you?" },
  { id: "v173", w: "kỹ sư",        pr: "kee suh",           en: "engineer",                     cat: "people",    lvl: 2, ex: "Anh ấy là kỹ sư.", exEn: "He is an engineer." },
  { id: "v174", w: "nhân viên",    pr: "nyuhn vyen",        en: "employee, staff",              cat: "people",    lvl: 2, ex: "Nhân viên ở đây rất lịch sự.", exEn: "The staff here are very polite." },
  { id: "v175", w: "tài xế",       pr: "tai seh",           en: "driver",                       cat: "people",    lvl: 2, ex: "Tài xế lái xe rất nhanh.", exEn: "The driver drives very fast." },
  // ---------- A2: verbs ----------
  { id: "v176", w: "nấu ăn",       pr: "now an",            en: "to cook",                      cat: "verbs",     lvl: 2, ex: "Tôi thích nấu ăn.", exEn: "I like cooking." },
  { id: "v177", w: "chạy",         pr: "chai",              en: "to run",                       cat: "sports",    lvl: 2, ex: "Tôi chạy mỗi sáng.", exEn: "I run every morning." },
  { id: "v178", w: "bơi",          pr: "buh-ee",            en: "to swim",                      cat: "sports",    lvl: 2, ex: "Bạn biết bơi không?", exEn: "Can you swim?" },
  { id: "v179", w: "chơi",         pr: "chuh-ee",           en: "to play",                      cat: "sports",    lvl: 2, ex: "Trẻ em chơi ở công viên.", exEn: "Children play in the park." },
  { id: "v180", w: "hát",          pr: "haht",              en: "to sing",                      cat: "sports",    lvl: 2, ex: "Cô ấy hát rất hay.", exEn: "She sings very well." },
  { id: "v181", w: "nhảy",         pr: "nyai",              en: "to dance; to jump",            cat: "sports",    lvl: 2, ex: "Chúng tôi nhảy cả đêm.", exEn: "We danced all night." },
  { id: "v182", w: "đá bóng",      pr: "dah bohng",         en: "to play football",             cat: "sports",    lvl: 2, ex: "Bọn trẻ đá bóng ngoài sân.", exEn: "The kids play football in the yard." },
  { id: "v183", w: "du lịch",      pr: "zoo lick",          en: "to travel; tourism",           cat: "sports",    lvl: 2, ex: "Tôi thích đi du lịch.", exEn: "I like traveling." },
  { id: "v184", w: "nghỉ",         pr: "ngee",              en: "to rest, to take a break",     cat: "verbs",     lvl: 2, ex: "Nghỉ một chút đi.", exEn: "Take a little break." },
  { id: "v185", w: "dậy",          pr: "zay",               en: "to get up",                    cat: "verbs",     lvl: 2, ex: "Tôi dậy lúc sáu giờ.", exEn: "I get up at six." },
  { id: "v186", w: "tắm",          pr: "tahm",              en: "to bathe, to shower",          cat: "verbs",     lvl: 2, ex: "Tôi tắm buổi tối.", exEn: "I shower in the evening." },
  { id: "v187", w: "mặc",          pr: "mack",              en: "to wear",                      cat: "verbs",     lvl: 2, ex: "Cô ấy mặc áo dài.", exEn: "She wears an ao dai." },
  { id: "v188", w: "lái xe",       pr: "lai seh",           en: "to drive",                     cat: "verbs",     lvl: 2, ex: "Bạn biết lái xe không?", exEn: "Can you drive?" },
  { id: "v189", w: "bắt đầu",      pr: "baht dow",          en: "to begin, to start",           cat: "verbs",     lvl: 2, ex: "Lớp học bắt đầu lúc tám giờ.", exEn: "Class starts at eight." },
  { id: "v190", w: "kết thúc",     pr: "ket took",          en: "to end, to finish",            cat: "verbs",     lvl: 2, ex: "Phim kết thúc rồi.", exEn: "The movie has ended." },
  { id: "v191", w: "tìm",          pr: "teem",              en: "to look for, to find",         cat: "verbs",     lvl: 2, ex: "Tôi đang tìm chìa khóa.", exEn: "I'm looking for my keys." },
  { id: "v192", w: "hỏi",          pr: "hoy",               en: "to ask",                       cat: "verbs",     lvl: 2, ex: "Tôi muốn hỏi một câu.", exEn: "I want to ask a question." },
  { id: "v193", w: "trả lời",      pr: "chah luh-ee",       en: "to answer",                    cat: "verbs",     lvl: 2, ex: "Hãy trả lời câu hỏi.", exEn: "Please answer the question." },
  { id: "v194", w: "nhớ",          pr: "nyuh",              en: "to remember; to miss",         cat: "verbs",     lvl: 2, ex: "Tôi nhớ nhà.", exEn: "I miss home." },
  { id: "v195", w: "quên",         pr: "kwen",              en: "to forget",                    cat: "verbs",     lvl: 2, ex: "Tôi quên mang tiền.", exEn: "I forgot to bring money." },
  { id: "v196", w: "nghĩ",         pr: "ngee",              en: "to think",                     cat: "verbs",     lvl: 2, ex: "Tôi nghĩ bạn đúng.", exEn: "I think you're right." },
  { id: "v197", w: "tin",          pr: "tin",               en: "to believe; news",             cat: "verbs",     lvl: 2, ex: "Tôi tin bạn.", exEn: "I believe you." },
  { id: "v198", w: "cho",          pr: "chaw",              en: "to give; for",                 cat: "verbs",     lvl: 2, ex: "Cho tôi một cốc nước.", exEn: "Give me a glass of water." },
  { id: "v199", w: "mang",         pr: "mahng",             en: "to bring, to carry",           cat: "verbs",     lvl: 2, ex: "Nhớ mang ô.", exEn: "Remember to bring an umbrella." },
  { id: "v200", w: "để",           pr: "deh",               en: "to put; in order to",          cat: "verbs",     lvl: 2, ex: "Để sách lên bàn.", exEn: "Put the book on the table." },
  { id: "v201", w: "đợi",          pr: "duh-ee",            en: "to wait",                      cat: "verbs",     lvl: 2, ex: "Đợi tôi một chút.", exEn: "Wait for me a moment." },
  { id: "v202", w: "thử",          pr: "tuh",               en: "to try",                       cat: "verbs",     lvl: 2, ex: "Tôi thử món này được không?", exEn: "May I try this dish?" },
  { id: "v203", w: "thay",         pr: "tai",               en: "to change, to replace",        cat: "verbs",     lvl: 2, ex: "Tôi cần thay quần áo.", exEn: "I need to change clothes." },
  { id: "v204", w: "dọn",          pr: "zon",               en: "to clean up, to tidy",         cat: "verbs",     lvl: 2, ex: "Tôi dọn phòng vào cuối tuần.", exEn: "I clean my room on the weekend." },
  { id: "v205", w: "rửa",          pr: "zuh-ah",            en: "to wash",                      cat: "verbs",     lvl: 2, ex: "Rửa tay trước khi ăn.", exEn: "Wash your hands before eating." },
  { id: "v206", w: "trả",          pr: "chah",              en: "to pay; to return (sth)",      cat: "verbs",     lvl: 2, ex: "Tôi trả tiền.", exEn: "I'll pay." },
  { id: "v207", w: "thuê",         pr: "tweh",              en: "to rent",                      cat: "verbs",     lvl: 2, ex: "Tôi thuê một căn hộ.", exEn: "I rent an apartment." },
  { id: "v208", w: "đặt",          pr: "daht",              en: "to book, to order; to place",  cat: "verbs",     lvl: 2, ex: "Tôi đặt bàn cho hai người.", exEn: "I booked a table for two." },
  { id: "v209", w: "gửi",          pr: "guh-ee",            en: "to send",                      cat: "verbs",     lvl: 2, ex: "Gửi tin nhắn cho tôi.", exEn: "Send me a message." },
  { id: "v210", w: "nhận",         pr: "nyuhn",             en: "to receive",                   cat: "verbs",     lvl: 2, ex: "Tôi nhận được thư.", exEn: "I received a letter." },
  { id: "v211", w: "sợ",           pr: "suh",               en: "to be afraid",                 cat: "verbs",     lvl: 2, ex: "Tôi sợ chó.", exEn: "I'm afraid of dogs." },
  { id: "v212", w: "cười",         pr: "kuh-ee",            en: "to laugh, to smile",           cat: "verbs",     lvl: 2, ex: "Cô ấy cười rất tươi.", exEn: "She smiles brightly." },
  { id: "v213", w: "khóc",         pr: "khohp",             en: "to cry",                       cat: "verbs",     lvl: 2, ex: "Em bé khóc.", exEn: "The baby is crying." },
  { id: "v214", w: "kết hôn",      pr: "ket hohn",          en: "to get married",               cat: "verbs",     lvl: 2, ex: "Họ kết hôn năm ngoái.", exEn: "They got married last year." },
  { id: "v215", w: "quyết định",   pr: "kwyet ding",        en: "to decide",                    cat: "verbs",     lvl: 2, ex: "Tôi quyết định ở lại.", exEn: "I decided to stay." },
  { id: "v216", w: "chuẩn bị",     pr: "choo-uhn bee",      en: "to prepare",                   cat: "verbs",     lvl: 2, ex: "Tôi chuẩn bị bữa tối.", exEn: "I'm preparing dinner." },
  { id: "v217", w: "giới thiệu",   pr: "zuh-ee tyew",       en: "to introduce",                 cat: "verbs",     lvl: 2, ex: "Tôi xin giới thiệu bạn tôi.", exEn: "Let me introduce my friend." },
  { id: "v218", w: "nên",          pr: "nen",               en: "should",                       cat: "verbs",     lvl: 2, ex: "Bạn nên nghỉ ngơi.", exEn: "You should rest." },
  { id: "v219", w: "phải",         pr: "fai",               en: "must, have to; right (side)",  cat: "verbs",     lvl: 2, ex: "Tôi phải đi bây giờ.", exEn: "I have to go now." },
  // ---------- A2: food & drink ----------
  { id: "v220", w: "bún",          pr: "boon",              en: "rice vermicelli",              cat: "food",      lvl: 2, ex: "Bún chả Hà Nội.", exEn: "Hanoi grilled pork with vermicelli." },
  { id: "v221", w: "gà",           pr: "gah",               en: "chicken",                      cat: "food",      lvl: 2, ex: "Phở gà.", exEn: "Chicken pho." },
  { id: "v222", w: "bò",           pr: "baw",               en: "beef; cow",                    cat: "food",      lvl: 2, ex: "Phở bò.", exEn: "Beef pho." },
  { id: "v223", w: "lợn",          pr: "luhn",              en: "pork; pig (North)",            cat: "food",      lvl: 2, ex: "Thịt lợn nướng.", exEn: "Grilled pork." },
  { id: "v224", w: "tôm",          pr: "tohm",              en: "shrimp",                       cat: "food",      lvl: 2, ex: "Tôm rất tươi.", exEn: "The shrimp is very fresh." },
  { id: "v225", w: "nước mắm",     pr: "nuh-uhk mahm",      en: "fish sauce",                   cat: "food",      lvl: 2, ex: "Chấm với nước mắm.", exEn: "Dip it in fish sauce." },
  { id: "v226", w: "chuối",        pr: "choo-oy",           en: "banana",                       cat: "food",      lvl: 2, ex: "Một nải chuối.", exEn: "A bunch of bananas." },
  { id: "v227", w: "xoài",         pr: "swai",              en: "mango",                        cat: "food",      lvl: 2, ex: "Xoài này rất ngọt.", exEn: "This mango is very sweet." },
  { id: "v228", w: "dừa",          pr: "zuh-ah",            en: "coconut",                      cat: "food",      lvl: 2, ex: "Nước dừa mát.", exEn: "Coconut water is refreshing." },
  { id: "v229", w: "cam",          pr: "kahm",              en: "orange",                       cat: "food",      lvl: 2, ex: "Nước cam.", exEn: "Orange juice." },
  { id: "v230", w: "bữa sáng",     pr: "buh-ah sahng",      en: "breakfast",                    cat: "food",      lvl: 2, ex: "Bữa sáng ăn phở.", exEn: "Pho for breakfast." },
  { id: "v231", w: "bữa tối",      pr: "buh-ah toy",        en: "dinner",                       cat: "food",      lvl: 2, ex: "Bữa tối lúc bảy giờ.", exEn: "Dinner is at seven." },
  { id: "v232", w: "món",          pr: "mon",               en: "dish (of food)",               cat: "food",      lvl: 2, ex: "Món này tên là gì?", exEn: "What's this dish called?" },
  { id: "v233", w: "cay",          pr: "kai",               en: "spicy",                        cat: "adjectives", lvl: 2, ex: "Món này cay quá.", exEn: "This dish is too spicy." },
  { id: "v234", w: "ngọt",         pr: "ngoht",             en: "sweet",                        cat: "adjectives", lvl: 2, ex: "Cà phê này ngọt.", exEn: "This coffee is sweet." },
  { id: "v235", w: "mặn",          pr: "mahn",              en: "salty",                        cat: "adjectives", lvl: 2, ex: "Canh hơi mặn.", exEn: "The soup is a bit salty." },
  { id: "v236", w: "khát",         pr: "khaht",             en: "thirsty",                      cat: "adjectives", lvl: 2, ex: "Tôi khát nước.", exEn: "I'm thirsty." },
  { id: "v237", w: "no",           pr: "naw",               en: "full (after eating)",          cat: "adjectives", lvl: 2, ex: "Tôi no rồi.", exEn: "I'm full." },
  { id: "v238", w: "thực đơn",     pr: "tuhk duhn",         en: "menu",                         cat: "food",      lvl: 2, ex: "Cho tôi xem thực đơn.", exEn: "Let me see the menu." },
  { id: "v239", w: "tính tiền",    pr: "ting tyen",         en: "to pay the bill",              cat: "phrases",   lvl: 2, ex: "Tính tiền đi!", exEn: "The bill, please!" },
  // ---------- A2: objects & home ----------
  { id: "v240", w: "bàn",          pr: "bahn",              en: "table",                        cat: "objects",   lvl: 2, ex: "Sách ở trên bàn.", exEn: "The book is on the table." },
  { id: "v241", w: "ghế",          pr: "geh",               en: "chair",                        cat: "objects",   lvl: 2, ex: "Ghế này rất thoải mái.", exEn: "This chair is very comfortable." },
  { id: "v242", w: "cửa",          pr: "kuh-ah",            en: "door",                         cat: "objects",   lvl: 2, ex: "Đóng cửa lại.", exEn: "Close the door." },
  { id: "v243", w: "phòng",        pr: "fohng",             en: "room",                         cat: "places",    lvl: 2, ex: "Phòng tôi nhỏ.", exEn: "My room is small." },
  { id: "v244", w: "điện thoại",   pr: "dyen twai",         en: "phone",                        cat: "objects",   lvl: 2, ex: "Điện thoại của tôi hết pin.", exEn: "My phone battery is dead." },
  { id: "v245", w: "máy tính",     pr: "mai ting",          en: "computer",                     cat: "objects",   lvl: 2, ex: "Tôi làm việc trên máy tính.", exEn: "I work on the computer." },
  { id: "v246", w: "ti vi",        pr: "tee vee",           en: "television",                   cat: "objects",   lvl: 2, ex: "Tôi xem ti vi buổi tối.", exEn: "I watch TV in the evening." },
  { id: "v247", w: "áo",           pr: "ow",                en: "shirt, top",                   cat: "objects",   lvl: 2, ex: "Áo này màu gì?", exEn: "What color is this shirt?" },
  { id: "v248", w: "quần",         pr: "kwuhn",             en: "trousers",                     cat: "objects",   lvl: 2, ex: "Quần này dài quá.", exEn: "These trousers are too long." },
  { id: "v249", w: "giày",         pr: "zai",               en: "shoes",                        cat: "objects",   lvl: 2, ex: "Đôi giày mới.", exEn: "A new pair of shoes." },
  { id: "v250", w: "mũ",           pr: "moo",               en: "hat",                          cat: "objects",   lvl: 2, ex: "Đội mũ khi ra ngoài.", exEn: "Wear a hat when going out." },
  { id: "v251", w: "túi",          pr: "too-ee",            en: "bag",                          cat: "objects",   lvl: 2, ex: "Túi này của ai?", exEn: "Whose bag is this?" },
  { id: "v252", w: "chìa khóa",    pr: "chee-ah khwah",     en: "key",                          cat: "objects",   lvl: 2, ex: "Tôi mất chìa khóa.", exEn: "I lost my keys." },
  { id: "v253", w: "ô",            pr: "oh",                en: "umbrella (North)",             cat: "objects",   lvl: 2, ex: "Trời mưa, mang ô đi.", exEn: "It's raining, take an umbrella." },
  { id: "v254", w: "vé",           pr: "veh",               en: "ticket",                       cat: "objects",   lvl: 2, ex: "Hai vé xem phim.", exEn: "Two movie tickets." },
  { id: "v255", w: "quà",          pr: "kwah",              en: "gift",                         cat: "objects",   lvl: 2, ex: "Đây là quà cho bạn.", exEn: "This is a gift for you." },
  { id: "v256", w: "ảnh",          pr: "ang",               en: "photo",                        cat: "objects",   lvl: 2, ex: "Chụp ảnh nhé!", exEn: "Let's take a photo!" },
  { id: "v257", w: "thuốc",        pr: "too-uhk",           en: "medicine",                     cat: "body",      lvl: 2, ex: "Uống thuốc sau bữa ăn.", exEn: "Take the medicine after meals." },
  // ---------- A2: places & transport ----------
  { id: "v258", w: "thành phố",    pr: "tang foh",          en: "city",                         cat: "places",    lvl: 2, ex: "Thành phố này rất lớn.", exEn: "This city is very big." },
  { id: "v259", w: "công viên",    pr: "kohng vyen",        en: "park",                         cat: "places",    lvl: 2, ex: "Đi dạo trong công viên.", exEn: "Take a walk in the park." },
  { id: "v260", w: "ngân hàng",    pr: "nguhn hahng",       en: "bank",                         cat: "places",    lvl: 2, ex: "Ngân hàng đóng cửa lúc năm giờ.", exEn: "The bank closes at five." },
  { id: "v261", w: "siêu thị",     pr: "syew tee",          en: "supermarket",                  cat: "places",    lvl: 2, ex: "Tôi đi siêu thị mua đồ.", exEn: "I go shopping at the supermarket." },
  { id: "v262", w: "văn phòng",    pr: "van fohng",         en: "office",                       cat: "places",    lvl: 2, ex: "Văn phòng ở tầng ba.", exEn: "The office is on the third floor." },
  { id: "v263", w: "biển",         pr: "byen",              en: "sea, beach",                   cat: "nature",    lvl: 2, ex: "Chúng tôi đi biển.", exEn: "We go to the beach." },
  { id: "v264", w: "núi",          pr: "noo-ee",            en: "mountain",                     cat: "nature",    lvl: 2, ex: "Núi rất cao.", exEn: "The mountain is very high." },
  { id: "v265", w: "sông",         pr: "sohng",             en: "river",                        cat: "nature",    lvl: 2, ex: "Sông Hồng ở Hà Nội.", exEn: "The Red River is in Hanoi." },
  { id: "v266", w: "bến xe",       pr: "ben seh",           en: "bus station",                  cat: "places",    lvl: 2, ex: "Bến xe ở đâu?", exEn: "Where is the bus station?" },
  { id: "v267", w: "ga",           pr: "gah",               en: "train station",                cat: "places",    lvl: 2, ex: "Ga Hà Nội.", exEn: "Hanoi station." },
  { id: "v268", w: "xe buýt",      pr: "seh bweet",         en: "bus",                          cat: "transport", lvl: 2, ex: "Tôi đi xe buýt đến trường.", exEn: "I take the bus to school." },
  { id: "v269", w: "tàu",          pr: "tow",               en: "train; ship",                  cat: "transport", lvl: 2, ex: "Đi tàu đến Huế.", exEn: "Take the train to Hue." },
  { id: "v270", w: "máy bay",      pr: "mai bai",           en: "airplane",                     cat: "transport", lvl: 2, ex: "Máy bay cất cánh lúc chín giờ.", exEn: "The plane takes off at nine." },
  { id: "v271", w: "xe đạp",       pr: "seh dahp",          en: "bicycle",                      cat: "transport", lvl: 2, ex: "Tôi đi xe đạp.", exEn: "I ride a bicycle." },
  { id: "v272", w: "taxi",         pr: "tak-see",           en: "taxi",                         cat: "transport", lvl: 2, ex: "Gọi taxi cho tôi.", exEn: "Call a taxi for me." },
  { id: "v273", w: "gần",          pr: "guhn",              en: "near",                         cat: "adjectives", lvl: 2, ex: "Nhà tôi gần đây.", exEn: "My house is near here." },
  { id: "v274", w: "xa",           pr: "sah",               en: "far",                          cat: "adjectives", lvl: 2, ex: "Sân bay xa không?", exEn: "Is the airport far?" },
  { id: "v275", w: "bên trái",     pr: "ben chai",          en: "left side",                    cat: "places",    lvl: 2, ex: "Rẽ bên trái.", exEn: "Turn left." },
  { id: "v276", w: "bên phải",     pr: "ben fai",           en: "right side",                   cat: "places",    lvl: 2, ex: "Ngân hàng ở bên phải.", exEn: "The bank is on the right." },
  { id: "v277", w: "thẳng",        pr: "tang",              en: "straight",                     cat: "places",    lvl: 2, ex: "Đi thẳng.", exEn: "Go straight." },
  // ---------- A2: time & weather ----------
  { id: "v278", w: "cuối tuần",    pr: "koo-oy too-uhn",    en: "weekend",                      cat: "time",      lvl: 2, ex: "Cuối tuần bạn làm gì?", exEn: "What do you do on the weekend?" },
  { id: "v279", w: "năm ngoái",    pr: "nam ngwai",         en: "last year",                    cat: "time",      lvl: 2, ex: "Năm ngoái tôi đi Đà Nẵng.", exEn: "Last year I went to Da Nang." },
  { id: "v280", w: "năm sau",      pr: "nam sow",           en: "next year",                    cat: "time",      lvl: 2, ex: "Năm sau tôi sẽ về.", exEn: "Next year I will return." },
  { id: "v281", w: "thứ hai",      pr: "tuh hai",           en: "Monday",                       cat: "time",      lvl: 2, ex: "Thứ hai tôi đi làm.", exEn: "On Monday I go to work." },
  { id: "v282", w: "chủ nhật",     pr: "choo nyuht",        en: "Sunday",                       cat: "time",      lvl: 2, ex: "Chủ nhật tôi nghỉ.", exEn: "On Sunday I rest." },
  { id: "v283", w: "sinh nhật",    pr: "sing nyuht",        en: "birthday",                     cat: "time",      lvl: 2, ex: "Chúc mừng sinh nhật!", exEn: "Happy birthday!" },
  { id: "v284", w: "Tết",          pr: "tet",               en: "Lunar New Year",               cat: "time",      lvl: 2, ex: "Chúc mừng năm mới!", exEn: "Happy New Year!" },
  { id: "v285", w: "thời tiết",    pr: "tuh-ee tyet",       en: "weather",                      cat: "nature",    lvl: 2, ex: "Thời tiết hôm nay thế nào?", exEn: "How's the weather today?" },
  { id: "v286", w: "mưa",          pr: "muh-ah",            en: "rain",                         cat: "nature",    lvl: 2, ex: "Trời đang mưa.", exEn: "It's raining." },
  { id: "v287", w: "nắng",         pr: "nang",              en: "sunny",                        cat: "nature",    lvl: 2, ex: "Hôm nay trời nắng.", exEn: "It's sunny today." },
  { id: "v288", w: "gió",          pr: "zoh",               en: "wind",                         cat: "nature",    lvl: 2, ex: "Gió rất mạnh.", exEn: "The wind is very strong." },
  { id: "v289", w: "mùa",          pr: "moo-ah",            en: "season",                       cat: "time",      lvl: 2, ex: "Mùa hè rất nóng.", exEn: "Summer is very hot." },
  { id: "v290", w: "sớm",          pr: "suhm",              en: "early",                        cat: "adverbs",   lvl: 2, ex: "Tôi dậy sớm.", exEn: "I get up early." },
  { id: "v291", w: "muộn",         pr: "moo-uhn",           en: "late",                         cat: "adverbs",   lvl: 2, ex: "Đừng đến muộn.", exEn: "Don't be late." },
  // ---------- A2: body & health ----------
  { id: "v292", w: "đầu",          pr: "dow",               en: "head",                         cat: "body",      lvl: 2, ex: "Tôi đau đầu.", exEn: "I have a headache." },
  { id: "v293", w: "mắt",          pr: "maht",              en: "eye",                          cat: "body",      lvl: 2, ex: "Mắt cô ấy rất đẹp.", exEn: "Her eyes are very beautiful." },
  { id: "v294", w: "tay",          pr: "tai",               en: "hand, arm",                    cat: "body",      lvl: 2, ex: "Rửa tay.", exEn: "Wash your hands." },
  { id: "v295", w: "chân",         pr: "chuhn",             en: "leg, foot",                    cat: "body",      lvl: 2, ex: "Chân tôi đau.", exEn: "My leg hurts." },
  { id: "v296", w: "đau",          pr: "dow",               en: "to hurt, painful",             cat: "body",      lvl: 2, ex: "Tôi đau bụng.", exEn: "I have a stomachache." },
  { id: "v297", w: "ốm",           pr: "ohm",               en: "sick (North)",                 cat: "body",      lvl: 2, ex: "Hôm nay tôi ốm.", exEn: "I'm sick today." },
  { id: "v298", w: "khỏe",         pr: "khweh",             en: "healthy, well",                cat: "body",      lvl: 2, ex: "Bạn có khỏe không?", exEn: "How are you? (Are you well?)" },
  { id: "v299", w: "sức khỏe",     pr: "suhk khweh",        en: "health",                       cat: "body",      lvl: 2, ex: "Sức khỏe là quan trọng nhất.", exEn: "Health is the most important." },
  // ---------- A2: adjectives & adverbs ----------
  { id: "v300", w: "cao",          pr: "kow",               en: "tall, high",                   cat: "adjectives", lvl: 2, ex: "Anh ấy rất cao.", exEn: "He is very tall." },
  { id: "v301", w: "thấp",         pr: "tuhp",              en: "short (height), low",          cat: "adjectives", lvl: 2, ex: "Cái bàn này thấp.", exEn: "This table is low." },
  { id: "v302", w: "dài",          pr: "zai",               en: "long",                         cat: "adjectives", lvl: 2, ex: "Con đường dài.", exEn: "A long road." },
  { id: "v303", w: "ngắn",         pr: "ngan",              en: "short (length)",               cat: "adjectives", lvl: 2, ex: "Tóc ngắn.", exEn: "Short hair." },
  { id: "v304", w: "nhanh",        pr: "nyang",             en: "fast",                         cat: "adjectives", lvl: 2, ex: "Anh ấy chạy rất nhanh.", exEn: "He runs very fast." },
  { id: "v305", w: "chậm",         pr: "chuhm",             en: "slow",                         cat: "adjectives", lvl: 2, ex: "Nói chậm hơn.", exEn: "Speak more slowly." },
  { id: "v306", w: "sạch",         pr: "sack",              en: "clean",                        cat: "adjectives", lvl: 2, ex: "Phòng rất sạch.", exEn: "The room is very clean." },
  { id: "v307", w: "bẩn",          pr: "buhn",              en: "dirty",                        cat: "adjectives", lvl: 2, ex: "Giày bẩn.", exEn: "Dirty shoes." },
  { id: "v308", w: "quan trọng",   pr: "kwahn chohng",      en: "important",                    cat: "adjectives", lvl: 2, ex: "Việc này rất quan trọng.", exEn: "This matter is very important." },
  { id: "v309", w: "buồn",         pr: "boo-uhn",           en: "sad",                          cat: "adjectives", lvl: 2, ex: "Đừng buồn.", exEn: "Don't be sad." },
  { id: "v310", w: "thú vị",       pr: "too vee",           en: "interesting",                  cat: "adjectives", lvl: 2, ex: "Cuốn sách này rất thú vị.", exEn: "This book is very interesting." },
  { id: "v311", w: "yên tĩnh",     pr: "yen ting",          en: "quiet",                        cat: "adjectives", lvl: 2, ex: "Nơi này rất yên tĩnh.", exEn: "This place is very quiet." },
  { id: "v312", w: "đông",         pr: "dohng",             en: "crowded; east; winter",        cat: "adjectives", lvl: 2, ex: "Chợ rất đông người.", exEn: "The market is very crowded." },
  { id: "v313", w: "đúng",         pr: "doong",             en: "correct, right",               cat: "adjectives", lvl: 2, ex: "Bạn nói đúng.", exEn: "You're right." },
  { id: "v314", w: "sai",          pr: "sai",               en: "wrong",                        cat: "adjectives", lvl: 2, ex: "Câu này sai.", exEn: "This sentence is wrong." },
  { id: "v315", w: "trẻ",          pr: "cheh",              en: "young",                        cat: "adjectives", lvl: 2, ex: "Cô ấy còn trẻ.", exEn: "She is still young." },
  { id: "v316", w: "già",          pr: "zah",               en: "old (people)",                 cat: "adjectives", lvl: 2, ex: "Ông tôi đã già.", exEn: "My grandfather is old." },
  { id: "v317", w: "luôn",         pr: "loo-uhn",           en: "always",                       cat: "adverbs",   lvl: 2, ex: "Tôi luôn dậy sớm.", exEn: "I always get up early." },
  { id: "v318", w: "thường",       pr: "tuh-uhng",          en: "usually, often",               cat: "adverbs",   lvl: 2, ex: "Tôi thường ăn phở.", exEn: "I often eat pho." },
  { id: "v319", w: "đôi khi",      pr: "doy khee",          en: "sometimes",                    cat: "adverbs",   lvl: 2, ex: "Đôi khi tôi đi bơi.", exEn: "Sometimes I go swimming." },
  { id: "v320", w: "chưa",         pr: "chuh-ah",           en: "not yet",                      cat: "adverbs",   lvl: 2, ex: "Tôi chưa ăn.", exEn: "I haven't eaten yet." },
  { id: "v321", w: "vẫn",          pr: "vuhn",              en: "still",                        cat: "adverbs",   lvl: 2, ex: "Tôi vẫn ở đây.", exEn: "I'm still here." },
  { id: "v322", w: "chỉ",          pr: "chee",              en: "only",                         cat: "adverbs",   lvl: 2, ex: "Tôi chỉ có mười nghìn.", exEn: "I only have ten thousand." },
  { id: "v323", w: "nhưng",        pr: "nyuhng",            en: "but",                          cat: "adverbs",   lvl: 2, ex: "Tôi muốn đi nhưng bận.", exEn: "I want to go, but I'm busy." },
  { id: "v324", w: "vì",           pr: "vee",               en: "because",                      cat: "adverbs",   lvl: 2, ex: "Tôi ở nhà vì mưa.", exEn: "I stay home because it's raining." },
  { id: "v325", w: "nếu",          pr: "neh-oo",            en: "if",                           cat: "adverbs",   lvl: 2, ex: "Nếu mưa, tôi không đi.", exEn: "If it rains, I won't go." },
  { id: "v326", w: "hoặc",         pr: "hwahk",             en: "or",                           cat: "adverbs",   lvl: 2, ex: "Trà hoặc cà phê?", exEn: "Tea or coffee?" },
  { id: "v327", w: "hơn",          pr: "huhn",              en: "more (than)",                  cat: "adverbs",   lvl: 2, ex: "Cái này đắt hơn.", exEn: "This one is more expensive." },
  { id: "v328", w: "nhất",         pr: "nyuht",             en: "most, -est",                   cat: "adverbs",   lvl: 2, ex: "Món ngon nhất.", exEn: "The most delicious dish." },
  { id: "v329", w: "màu",          pr: "mow",               en: "color",                        cat: "misc",      lvl: 2, ex: "Bạn thích màu gì?", exEn: "What color do you like?" },
  { id: "v330", w: "đỏ",           pr: "daw",               en: "red",                          cat: "adjectives", lvl: 2, ex: "Áo màu đỏ.", exEn: "A red shirt." },
  { id: "v331", w: "xanh",         pr: "sang",              en: "blue / green",                 cat: "adjectives", lvl: 2, ex: "Bầu trời màu xanh.", exEn: "The sky is blue." },
  { id: "v332", w: "trắng",        pr: "chang",             en: "white",                        cat: "adjectives", lvl: 2, ex: "Áo trắng.", exEn: "A white shirt." },
  { id: "v333", w: "đen",          pr: "den",               en: "black",                        cat: "adjectives", lvl: 2, ex: "Cà phê đen.", exEn: "Black coffee." },
  { id: "v334", w: "công việc",    pr: "kohng vyek",        en: "work, job",                    cat: "study",     lvl: 2, ex: "Công việc của bạn là gì?", exEn: "What is your job?" },
  { id: "v335", w: "bài tập",      pr: "bai tuhp",          en: "homework, exercise",           cat: "study",     lvl: 2, ex: "Tôi làm bài tập.", exEn: "I do my homework." },
  { id: "v336", w: "lớp",          pr: "luhp",              en: "class",                        cat: "study",     lvl: 2, ex: "Lớp học tiếng Việt.", exEn: "Vietnamese class." },
  { id: "v337", w: "câu hỏi",      pr: "kow hoy",           en: "question",                     cat: "study",     lvl: 2, ex: "Tôi có một câu hỏi.", exEn: "I have a question." },
  { id: "v338", w: "từ",           pr: "tuh",               en: "word; from",                   cat: "study",     lvl: 2, ex: "Từ này nghĩa là gì?", exEn: "What does this word mean?" },
  { id: "v339", w: "chó",          pr: "choh",              en: "dog",                          cat: "animals",   lvl: 2, ex: "Tôi có một con chó.", exEn: "I have a dog." },
  { id: "v340", w: "mèo",          pr: "meh-oo",            en: "cat",                          cat: "animals",   lvl: 2, ex: "Con mèo đang ngủ.", exEn: "The cat is sleeping." },
  { id: "v341", w: "chim",         pr: "chim",              en: "bird",                         cat: "animals",   lvl: 2, ex: "Chim hót buổi sáng.", exEn: "Birds sing in the morning." },
  { id: "v342", w: "cây",          pr: "kay",               en: "tree, plant",                  cat: "nature",    lvl: 2, ex: "Cây này rất cao.", exEn: "This tree is very tall." },
  { id: "v343", w: "hoa",          pr: "hwah",              en: "flower",                       cat: "nature",    lvl: 2, ex: "Hoa rất đẹp.", exEn: "The flowers are beautiful." },
  { id: "v344", w: "trời",         pr: "chuh-ee",           en: "sky, weather; heaven",         cat: "nature",    lvl: 2, ex: "Trời đẹp quá!", exEn: "What nice weather!" },
  { id: "v345", w: "nhạc",         pr: "nyahk",             en: "music",                        cat: "sports",    lvl: 2, ex: "Tôi thích nghe nhạc.", exEn: "I like listening to music." },
  { id: "v346", w: "phim",         pr: "feem",              en: "movie",                        cat: "sports",    lvl: 2, ex: "Tối nay xem phim nhé.", exEn: "Let's watch a movie tonight." },
  { id: "v347", w: "chụp ảnh",     pr: "choop ang",         en: "to take photos",               cat: "sports",    lvl: 2, ex: "Tôi thích chụp ảnh.", exEn: "I like taking photos." },
  { id: "v348", w: "đồng",         pr: "dohng",             en: "dong (Vietnamese currency)",   cat: "measure",   lvl: 2, ex: "Năm mươi nghìn đồng.", exEn: "Fifty thousand dong." },
  { id: "v349", w: "đôi",          pr: "doy",               en: "pair",                         cat: "measure",   lvl: 2, ex: "Một đôi giày.", exEn: "A pair of shoes." },
  { id: "v350", w: "quyển",        pr: "kwyen",             en: "(classifier for books)",       cat: "measure",   lvl: 2, ex: "Ba quyển sách.", exEn: "Three books." }
];
