/* HSK 2 vocabulary — 150 words (HSK 2.0 standard list, 2012).
 * Word list and pinyin follow the official list (via github.com/glxxyz/hskhsk.com, MIT).
 * Fields: id, hz (hanzi), py (pinyin), en, cat, ex (example), exPy, exEn
 */
window.HSK2_WORDS = [
  { id: 151, hz: "吧",     py: "ba",        en: "(particle: suggestion, ...right?)", cat: "particles", ex: "我们走吧。", exPy: "Wǒmen zǒu ba.", exEn: "Let's go." },
  { id: 152, hz: "白",     py: "bái",       en: "white",                          cat: "adjectives", ex: "我喜欢白色的衣服。", exPy: "Wǒ xǐhuan báisè de yīfu.", exEn: "I like white clothes." },
  { id: 153, hz: "百",     py: "bǎi",       en: "hundred",                        cat: "numbers",    ex: "这本书一百块。", exPy: "Zhè běn shū yìbǎi kuài.", exEn: "This book costs 100 yuan." },
  { id: 154, hz: "帮助",   py: "bāngzhù",   en: "to help; help",                  cat: "verbs",      ex: "谢谢你的帮助。", exPy: "Xièxie nǐ de bāngzhù.", exEn: "Thanks for your help." },
  { id: 155, hz: "报纸",   py: "bàozhǐ",    en: "newspaper",                      cat: "objects",    ex: "爸爸在看报纸。", exPy: "Bàba zài kàn bàozhǐ.", exEn: "Dad is reading the newspaper." },
  { id: 156, hz: "比",     py: "bǐ",        en: "than; to compare",               cat: "particles",  ex: "他比我高。", exPy: "Tā bǐ wǒ gāo.", exEn: "He is taller than me." },
  { id: 157, hz: "别",     py: "bié",       en: "don't; other",                   cat: "adverbs",    ex: "别说话！", exPy: "Bié shuōhuà!", exEn: "Don't talk!" },
  { id: 158, hz: "宾馆",   py: "bīnguǎn",   en: "hotel, guesthouse",              cat: "places",     ex: "我们住在这个宾馆。", exPy: "Wǒmen zhù zài zhège bīnguǎn.", exEn: "We are staying at this hotel." },
  { id: 159, hz: "长",     py: "cháng",     en: "long",                           cat: "adjectives", ex: "这条路很长。", exPy: "Zhè tiáo lù hěn cháng.", exEn: "This road is very long." },
  { id: 160, hz: "唱歌",   py: "chànggē",   en: "to sing",                        cat: "sports",     ex: "她喜欢唱歌。", exPy: "Tā xǐhuan chànggē.", exEn: "She likes singing." },
  { id: 161, hz: "出",     py: "chū",       en: "to go out, to come out",         cat: "verbs",      ex: "他出去了。", exPy: "Tā chūqù le.", exEn: "He went out." },
  { id: 162, hz: "穿",     py: "chuān",     en: "to wear, to put on",             cat: "verbs",      ex: "今天很冷，多穿衣服。", exPy: "Jīntiān hěn lěng, duō chuān yīfu.", exEn: "It's cold today, wear more clothes." },
  { id: 163, hz: "次",     py: "cì",        en: "time, occurrence (measure word)", cat: "measure",   ex: "我去过一次北京。", exPy: "Wǒ qùguo yí cì Běijīng.", exEn: "I have been to Beijing once." },
  { id: 164, hz: "从",     py: "cóng",      en: "from",                           cat: "particles",  ex: "我从中国来。", exPy: "Wǒ cóng Zhōngguó lái.", exEn: "I come from China." },
  { id: 165, hz: "错",     py: "cuò",       en: "wrong; mistake",                 cat: "adjectives", ex: "这个字写错了。", exPy: "Zhège zì xiě cuò le.", exEn: "This character is written wrong." },
  { id: 166, hz: "打篮球", py: "dǎ lánqiú", en: "to play basketball",             cat: "sports",     ex: "他每天打篮球。", exPy: "Tā měi tiān dǎ lánqiú.", exEn: "He plays basketball every day." },
  { id: 167, hz: "大家",   py: "dàjiā",     en: "everyone",                       cat: "pronouns",   ex: "大家好！", exPy: "Dàjiā hǎo!", exEn: "Hello everyone!" },
  { id: 168, hz: "到",     py: "dào",       en: "to arrive; to, until",           cat: "verbs",      ex: "我到家了。", exPy: "Wǒ dào jiā le.", exEn: "I have arrived home." },
  { id: 169, hz: "得",     py: "de",        en: "(complement particle)",          cat: "particles",  ex: "她说得很好。", exPy: "Tā shuō de hěn hǎo.", exEn: "She speaks very well." },
  { id: 170, hz: "等",     py: "děng",      en: "to wait; etc.",                  cat: "verbs",      ex: "请等一下。", exPy: "Qǐng děng yíxià.", exEn: "Please wait a moment." },
  { id: 171, hz: "弟弟",   py: "dìdi",      en: "younger brother",                cat: "family",     ex: "我弟弟十岁。", exPy: "Wǒ dìdi shí suì.", exEn: "My younger brother is ten." },
  { id: 172, hz: "第一",   py: "dìyī",      en: "first",                          cat: "numbers",    ex: "这是我第一次来。", exPy: "Zhè shì wǒ dì yī cì lái.", exEn: "This is my first time here." },
  { id: 173, hz: "懂",     py: "dǒng",      en: "to understand",                  cat: "verbs",      ex: "我懂了。", exPy: "Wǒ dǒng le.", exEn: "I understand." },
  { id: 174, hz: "对",     py: "duì",       en: "correct; towards",               cat: "adjectives", ex: "你说得对。", exPy: "Nǐ shuō de duì.", exEn: "You're right." },
  { id: 175, hz: "房间",   py: "fángjiān",  en: "room",                           cat: "places",     ex: "我的房间很小。", exPy: "Wǒ de fángjiān hěn xiǎo.", exEn: "My room is very small." },
  { id: 176, hz: "非常",   py: "fēicháng",  en: "very, extremely",                cat: "adverbs",    ex: "我非常喜欢这里。", exPy: "Wǒ fēicháng xǐhuan zhèlǐ.", exEn: "I like it here very much." },
  { id: 177, hz: "服务员", py: "fúwùyuán",  en: "waiter, waitress",               cat: "people",     ex: "服务员，买单！", exPy: "Fúwùyuán, mǎidān!", exEn: "Waiter, the bill please!" },
  { id: 178, hz: "高",     py: "gāo",       en: "tall, high",                     cat: "adjectives", ex: "他很高。", exPy: "Tā hěn gāo.", exEn: "He is very tall." },
  { id: 179, hz: "告诉",   py: "gàosu",     en: "to tell",                        cat: "verbs",      ex: "请告诉我你的名字。", exPy: "Qǐng gàosu wǒ nǐ de míngzi.", exEn: "Please tell me your name." },
  { id: 180, hz: "哥哥",   py: "gēge",      en: "older brother",                  cat: "family",     ex: "我哥哥是老师。", exPy: "Wǒ gēge shì lǎoshī.", exEn: "My older brother is a teacher." },
  { id: 181, hz: "给",     py: "gěi",       en: "to give; to, for",               cat: "verbs",      ex: "请给我一杯水。", exPy: "Qǐng gěi wǒ yì bēi shuǐ.", exEn: "Please give me a glass of water." },
  { id: 182, hz: "公共汽车", py: "gōnggòng qìchē", en: "bus",                    cat: "transport",  ex: "我坐公共汽车上班。", exPy: "Wǒ zuò gōnggòng qìchē shàngbān.", exEn: "I take the bus to work." },
  { id: 183, hz: "公司",   py: "gōngsī",    en: "company",                        cat: "places",     ex: "他在一家公司工作。", exPy: "Tā zài yì jiā gōngsī gōngzuò.", exEn: "He works at a company." },
  { id: 184, hz: "贵",     py: "guì",       en: "expensive",                      cat: "adjectives", ex: "这个太贵了。", exPy: "Zhège tài guì le.", exEn: "This is too expensive." },
  { id: 185, hz: "过",     py: "guò",       en: "to pass, to cross; to spend (time)", cat: "verbs",  ex: "过马路要小心。", exPy: "Guò mǎlù yào xiǎoxīn.", exEn: "Be careful crossing the road." },
  { id: 186, hz: "还",     py: "hái",       en: "still, also",                    cat: "adverbs",    ex: "他还在睡觉。", exPy: "Tā hái zài shuìjiào.", exEn: "He is still sleeping." },
  { id: 187, hz: "孩子",   py: "háizi",     en: "child",                          cat: "family",     ex: "他们有两个孩子。", exPy: "Tāmen yǒu liǎng gè háizi.", exEn: "They have two children." },
  { id: 188, hz: "好吃",   py: "hǎochī",    en: "delicious",                      cat: "adjectives", ex: "这个菜真好吃！", exPy: "Zhège cài zhēn hǎochī!", exEn: "This dish is really delicious!" },
  { id: 189, hz: "黑",     py: "hēi",       en: "black; dark",                    cat: "adjectives", ex: "天黑了。", exPy: "Tiān hēi le.", exEn: "It's getting dark." },
  { id: 190, hz: "红",     py: "hóng",      en: "red",                            cat: "adjectives", ex: "她穿着红衣服。", exPy: "Tā chuānzhe hóng yīfu.", exEn: "She is wearing red clothes." },
  { id: 191, hz: "火车站", py: "huǒchēzhàn", en: "train station",                 cat: "places",     ex: "火车站在哪儿？", exPy: "Huǒchēzhàn zài nǎr?", exEn: "Where is the train station?" },
  { id: 192, hz: "机场",   py: "jīchǎng",   en: "airport",                        cat: "places",     ex: "我去机场接朋友。", exPy: "Wǒ qù jīchǎng jiē péngyou.", exEn: "I'm going to the airport to pick up a friend." },
  { id: 193, hz: "鸡蛋",   py: "jīdàn",     en: "egg",                            cat: "food",       ex: "我早上吃两个鸡蛋。", exPy: "Wǒ zǎoshang chī liǎng gè jīdàn.", exEn: "I eat two eggs in the morning." },
  { id: 194, hz: "件",     py: "jiàn",      en: "(measure word for clothes, matters)", cat: "measure", ex: "我买了一件衣服。", exPy: "Wǒ mǎi le yí jiàn yīfu.", exEn: "I bought a piece of clothing." },
  { id: 195, hz: "教室",   py: "jiàoshì",   en: "classroom",                      cat: "places",     ex: "教室里有很多学生。", exPy: "Jiàoshì lǐ yǒu hěn duō xuésheng.", exEn: "There are many students in the classroom." },
  { id: 196, hz: "姐姐",   py: "jiějie",    en: "older sister",                   cat: "family",     ex: "我姐姐在北京工作。", exPy: "Wǒ jiějie zài Běijīng gōngzuò.", exEn: "My older sister works in Beijing." },
  { id: 197, hz: "介绍",   py: "jièshào",   en: "to introduce",                   cat: "verbs",      ex: "我来介绍一下。", exPy: "Wǒ lái jièshào yíxià.", exEn: "Let me introduce." },
  { id: 198, hz: "进",     py: "jìn",       en: "to enter",                       cat: "verbs",      ex: "请进！", exPy: "Qǐng jìn!", exEn: "Please come in!" },
  { id: 199, hz: "近",     py: "jìn",       en: "near, close",                    cat: "adjectives", ex: "学校离我家很近。", exPy: "Xuéxiào lí wǒ jiā hěn jìn.", exEn: "The school is close to my home." },
  { id: 200, hz: "就",     py: "jiù",       en: "then, right away; just",         cat: "adverbs",    ex: "我马上就来。", exPy: "Wǒ mǎshàng jiù lái.", exEn: "I'll come right away." },
  { id: 201, hz: "觉得",   py: "juéde",     en: "to feel, to think",              cat: "verbs",      ex: "我觉得很好。", exPy: "Wǒ juéde hěn hǎo.", exEn: "I think it's very good." },
  { id: 202, hz: "咖啡",   py: "kāfēi",     en: "coffee",                         cat: "food",       ex: "我每天喝咖啡。", exPy: "Wǒ měi tiān hē kāfēi.", exEn: "I drink coffee every day." },
  { id: 203, hz: "开始",   py: "kāishǐ",    en: "to begin, to start",             cat: "verbs",      ex: "我们开始上课吧。", exPy: "Wǒmen kāishǐ shàngkè ba.", exEn: "Let's start the class." },
  { id: 204, hz: "考试",   py: "kǎoshì",    en: "exam; to take an exam",          cat: "study",      ex: "明天有考试。", exPy: "Míngtiān yǒu kǎoshì.", exEn: "There is an exam tomorrow." },
  { id: 205, hz: "可能",   py: "kěnéng",    en: "maybe, possibly",                cat: "adverbs",    ex: "明天可能下雨。", exPy: "Míngtiān kěnéng xiàyǔ.", exEn: "It may rain tomorrow." },
  { id: 206, hz: "可以",   py: "kěyǐ",      en: "can, may",                       cat: "verbs",      ex: "我可以进来吗？", exPy: "Wǒ kěyǐ jìnlái ma?", exEn: "May I come in?" },
  { id: 207, hz: "课",     py: "kè",        en: "class, lesson",                  cat: "study",      ex: "我今天有三节课。", exPy: "Wǒ jīntiān yǒu sān jié kè.", exEn: "I have three classes today." },
  { id: 208, hz: "快",     py: "kuài",      en: "fast, quick",                    cat: "adjectives", ex: "他跑得很快。", exPy: "Tā pǎo de hěn kuài.", exEn: "He runs very fast." },
  { id: 209, hz: "快乐",   py: "kuàilè",    en: "happy",                          cat: "adjectives", ex: "生日快乐！", exPy: "Shēngrì kuàilè!", exEn: "Happy birthday!" },
  { id: 210, hz: "累",     py: "lèi",       en: "tired",                          cat: "adjectives", ex: "我今天很累。", exPy: "Wǒ jīntiān hěn lèi.", exEn: "I'm very tired today." },
  { id: 211, hz: "离",     py: "lí",        en: "away from, from",                cat: "particles",  ex: "我家离公司很远。", exPy: "Wǒ jiā lí gōngsī hěn yuǎn.", exEn: "My home is far from the company." },
  { id: 212, hz: "两",     py: "liǎng",     en: "two (before measure words)",     cat: "numbers",    ex: "我要两杯茶。", exPy: "Wǒ yào liǎng bēi chá.", exEn: "I want two cups of tea." },
  { id: 213, hz: "零",     py: "líng",      en: "zero",                           cat: "numbers",    ex: "现在十点零五分。", exPy: "Xiànzài shí diǎn líng wǔ fēn.", exEn: "It's 10:05 now." },
  { id: 214, hz: "路",     py: "lù",        en: "road, way",                      cat: "places",     ex: "这条路很长。", exPy: "Zhè tiáo lù hěn cháng.", exEn: "This road is very long." },
  { id: 215, hz: "旅游",   py: "lǚyóu",     en: "to travel; tourism",             cat: "sports",     ex: "我喜欢去旅游。", exPy: "Wǒ xǐhuan qù lǚyóu.", exEn: "I like to travel." },
  { id: 216, hz: "卖",     py: "mài",       en: "to sell",                        cat: "verbs",      ex: "这里卖水果。", exPy: "Zhèlǐ mài shuǐguǒ.", exEn: "Fruit is sold here." },
  { id: 217, hz: "慢",     py: "màn",       en: "slow",                           cat: "adjectives", ex: "请说慢一点儿。", exPy: "Qǐng shuō màn yìdiǎnr.", exEn: "Please speak a little slower." },
  { id: 218, hz: "忙",     py: "máng",      en: "busy",                           cat: "adjectives", ex: "我今天很忙。", exPy: "Wǒ jīntiān hěn máng.", exEn: "I'm very busy today." },
  { id: 219, hz: "每",     py: "měi",       en: "every, each",                    cat: "pronouns",   ex: "我每天学习汉语。", exPy: "Wǒ měi tiān xuéxí Hànyǔ.", exEn: "I study Chinese every day." },
  { id: 220, hz: "妹妹",   py: "mèimei",    en: "younger sister",                 cat: "family",     ex: "我妹妹很可爱。", exPy: "Wǒ mèimei hěn kě'ài.", exEn: "My younger sister is very cute." },
  { id: 221, hz: "门",     py: "mén",       en: "door, gate",                     cat: "objects",    ex: "请关门。", exPy: "Qǐng guān mén.", exEn: "Please close the door." },
  { id: 222, hz: "面条",   py: "miàntiáo",  en: "noodles",                        cat: "food",       ex: "我中午吃面条。", exPy: "Wǒ zhōngwǔ chī miàntiáo.", exEn: "I eat noodles at noon." },
  { id: 223, hz: "男",     py: "nán",       en: "male, man",                      cat: "people",     ex: "他是我的男朋友。", exPy: "Tā shì wǒ de nán péngyou.", exEn: "He is my boyfriend." },
  { id: 224, hz: "您",     py: "nín",       en: "you (polite)",                   cat: "pronouns",   ex: "您好！", exPy: "Nín hǎo!", exEn: "Hello (polite)!" },
  { id: 225, hz: "牛奶",   py: "niúnǎi",    en: "milk",                           cat: "food",       ex: "孩子喜欢喝牛奶。", exPy: "Háizi xǐhuan hē niúnǎi.", exEn: "Children like to drink milk." },
  { id: 226, hz: "女",     py: "nǚ",        en: "female, woman",                  cat: "people",     ex: "她是我的女朋友。", exPy: "Tā shì wǒ de nǚ péngyou.", exEn: "She is my girlfriend." },
  { id: 227, hz: "旁边",   py: "pángbiān",  en: "beside, next to",                cat: "places",     ex: "银行在学校旁边。", exPy: "Yínháng zài xuéxiào pángbiān.", exEn: "The bank is next to the school." },
  { id: 228, hz: "跑步",   py: "pǎobù",     en: "to run, to jog",                 cat: "sports",     ex: "我早上跑步。", exPy: "Wǒ zǎoshang pǎobù.", exEn: "I go running in the morning." },
  { id: 229, hz: "便宜",   py: "piányi",    en: "cheap",                          cat: "adjectives", ex: "这个很便宜。", exPy: "Zhège hěn piányi.", exEn: "This is very cheap." },
  { id: 230, hz: "票",     py: "piào",      en: "ticket",                         cat: "objects",    ex: "我买了两张票。", exPy: "Wǒ mǎi le liǎng zhāng piào.", exEn: "I bought two tickets." },
  { id: 231, hz: "妻子",   py: "qīzi",      en: "wife",                           cat: "family",     ex: "这是我的妻子。", exPy: "Zhè shì wǒ de qīzi.", exEn: "This is my wife." },
  { id: 232, hz: "起床",   py: "qǐchuáng",  en: "to get up (out of bed)",         cat: "verbs",      ex: "我七点起床。", exPy: "Wǒ qī diǎn qǐchuáng.", exEn: "I get up at seven." },
  { id: 233, hz: "千",     py: "qiān",      en: "thousand",                       cat: "numbers",    ex: "这个手机三千块。", exPy: "Zhège shǒujī sānqiān kuài.", exEn: "This phone costs 3,000 yuan." },
  { id: 234, hz: "铅笔",   py: "qiānbǐ",    en: "pencil",                         cat: "objects",    ex: "请用铅笔写。", exPy: "Qǐng yòng qiānbǐ xiě.", exEn: "Please write with a pencil." },
  { id: 235, hz: "晴",     py: "qíng",      en: "sunny, clear (weather)",         cat: "nature",     ex: "今天是晴天。", exPy: "Jīntiān shì qíngtiān.", exEn: "Today is a sunny day." },
  { id: 236, hz: "去年",   py: "qùnián",    en: "last year",                      cat: "time",       ex: "我去年去了中国。", exPy: "Wǒ qùnián qù le Zhōngguó.", exEn: "I went to China last year." },
  { id: 237, hz: "让",     py: "ràng",      en: "to let, to make (someone do)",   cat: "verbs",      ex: "让我看看。", exPy: "Ràng wǒ kànkan.", exEn: "Let me have a look." },
  { id: 238, hz: "日",     py: "rì",        en: "day; sun",                       cat: "time",       ex: "今天是五月一日。", exPy: "Jīntiān shì wǔ yuè yī rì.", exEn: "Today is May 1st." },
  { id: 239, hz: "上班",   py: "shàngbān",  en: "to go to work",                  cat: "study",      ex: "我每天八点上班。", exPy: "Wǒ měi tiān bā diǎn shàngbān.", exEn: "I go to work at eight every day." },
  { id: 240, hz: "身体",   py: "shēntǐ",    en: "body; health",                   cat: "body",       ex: "他身体很好。", exPy: "Tā shēntǐ hěn hǎo.", exEn: "He is in good health." },
  { id: 241, hz: "生病",   py: "shēngbìng", en: "to get sick",                    cat: "body",       ex: "他生病了，没来上课。", exPy: "Tā shēngbìng le, méi lái shàngkè.", exEn: "He got sick and didn't come to class." },
  { id: 242, hz: "生日",   py: "shēngrì",   en: "birthday",                       cat: "time",       ex: "今天是我的生日。", exPy: "Jīntiān shì wǒ de shēngrì.", exEn: "Today is my birthday." },
  { id: 243, hz: "时间",   py: "shíjiān",   en: "time",                           cat: "time",       ex: "我没有时间。", exPy: "Wǒ méiyǒu shíjiān.", exEn: "I don't have time." },
  { id: 244, hz: "事情",   py: "shìqing",   en: "matter, thing, affair",          cat: "misc",       ex: "我有一件事情要告诉你。", exPy: "Wǒ yǒu yí jiàn shìqing yào gàosu nǐ.", exEn: "I have something to tell you." },
  { id: 245, hz: "手表",   py: "shǒubiǎo",  en: "wristwatch",                     cat: "objects",    ex: "这是我的新手表。", exPy: "Zhè shì wǒ de xīn shǒubiǎo.", exEn: "This is my new watch." },
  { id: 246, hz: "手机",   py: "shǒujī",    en: "mobile phone",                   cat: "objects",    ex: "我的手机在哪儿？", exPy: "Wǒ de shǒujī zài nǎr?", exEn: "Where is my phone?" },
  { id: 247, hz: "说话",   py: "shuōhuà",   en: "to talk, to speak",              cat: "verbs",      ex: "请不要说话。", exPy: "Qǐng bú yào shuōhuà.", exEn: "Please don't talk." },
  { id: 248, hz: "送",     py: "sòng",      en: "to give (a gift); to deliver; to see off", cat: "verbs", ex: "我送你一本书。", exPy: "Wǒ sòng nǐ yì běn shū.", exEn: "I'll give you a book." },
  { id: 249, hz: "虽然",   py: "suīrán",    en: "although",                       cat: "adverbs",    ex: "虽然很累，但是很高兴。", exPy: "Suīrán hěn lèi, dànshì hěn gāoxìng.", exEn: "Although tired, I'm very happy." },
  { id: 250, hz: "但是",   py: "dànshì",    en: "but, however",                   cat: "adverbs",    ex: "我想去，但是没有时间。", exPy: "Wǒ xiǎng qù, dànshì méiyǒu shíjiān.", exEn: "I want to go, but I have no time." },
  { id: 251, hz: "它",     py: "tā",        en: "it",                             cat: "pronouns",   ex: "它是我的猫。", exPy: "Tā shì wǒ de māo.", exEn: "It is my cat." },
  { id: 252, hz: "踢足球", py: "tī zúqiú",  en: "to play football (soccer)",      cat: "sports",     ex: "他们在踢足球。", exPy: "Tāmen zài tī zúqiú.", exEn: "They are playing football." },
  { id: 253, hz: "题",     py: "tí",        en: "question, problem (on a test)",  cat: "study",      ex: "这个题很难。", exPy: "Zhège tí hěn nán.", exEn: "This question is very hard." },
  { id: 254, hz: "跳舞",   py: "tiàowǔ",    en: "to dance",                       cat: "sports",     ex: "她跳舞跳得很好。", exPy: "Tā tiàowǔ tiào de hěn hǎo.", exEn: "She dances very well." },
  { id: 255, hz: "外",     py: "wài",       en: "outside",                        cat: "places",     ex: "他在外面等你。", exPy: "Tā zài wàimiàn děng nǐ.", exEn: "He is waiting for you outside." },
  { id: 256, hz: "完",     py: "wán",       en: "to finish; finished",            cat: "verbs",      ex: "我吃完了。", exPy: "Wǒ chī wán le.", exEn: "I have finished eating." },
  { id: 257, hz: "玩",     py: "wán",       en: "to play, to have fun",           cat: "verbs",      ex: "孩子们在外面玩。", exPy: "Háizimen zài wàimiàn wán.", exEn: "The children are playing outside." },
  { id: 258, hz: "晚上",   py: "wǎnshang",  en: "evening, night",                 cat: "time",       ex: "晚上我们看电影。", exPy: "Wǎnshang wǒmen kàn diànyǐng.", exEn: "In the evening we watch a movie." },
  { id: 259, hz: "往",     py: "wǎng",      en: "towards, to",                    cat: "particles",  ex: "往前走。", exPy: "Wǎng qián zǒu.", exEn: "Go straight ahead." },
  { id: 260, hz: "为什么", py: "wèishénme", en: "why",                            cat: "question",   ex: "你为什么学汉语？", exPy: "Nǐ wèishénme xué Hànyǔ?", exEn: "Why do you study Chinese?" },
  { id: 261, hz: "问",     py: "wèn",       en: "to ask",                         cat: "verbs",      ex: "我想问一个问题。", exPy: "Wǒ xiǎng wèn yí gè wèntí.", exEn: "I'd like to ask a question." },
  { id: 262, hz: "问题",   py: "wèntí",     en: "question, problem",              cat: "misc",       ex: "没问题！", exPy: "Méi wèntí!", exEn: "No problem!" },
  { id: 263, hz: "西瓜",   py: "xīguā",     en: "watermelon",                     cat: "food",       ex: "夏天我爱吃西瓜。", exPy: "Xiàtiān wǒ ài chī xīguā.", exEn: "In summer I love eating watermelon." },
  { id: 264, hz: "希望",   py: "xīwàng",    en: "to hope; hope",                  cat: "verbs",      ex: "希望你喜欢。", exPy: "Xīwàng nǐ xǐhuan.", exEn: "I hope you like it." },
  { id: 265, hz: "洗",     py: "xǐ",        en: "to wash",                        cat: "verbs",      ex: "吃饭前要洗手。", exPy: "Chīfàn qián yào xǐ shǒu.", exEn: "Wash your hands before eating." },
  { id: 266, hz: "小时",   py: "xiǎoshí",   en: "hour",                           cat: "time",       ex: "我等了两个小时。", exPy: "Wǒ děng le liǎng gè xiǎoshí.", exEn: "I waited for two hours." },
  { id: 267, hz: "笑",     py: "xiào",      en: "to laugh, to smile",             cat: "verbs",      ex: "她笑了。", exPy: "Tā xiào le.", exEn: "She smiled." },
  { id: 268, hz: "新",     py: "xīn",       en: "new",                            cat: "adjectives", ex: "这是我的新手机。", exPy: "Zhè shì wǒ de xīn shǒujī.", exEn: "This is my new phone." },
  { id: 269, hz: "姓",     py: "xìng",      en: "surname; to be surnamed",        cat: "people",     ex: "您姓什么？", exPy: "Nín xìng shénme?", exEn: "What is your surname?" },
  { id: 270, hz: "休息",   py: "xiūxi",     en: "to rest",                        cat: "verbs",      ex: "我们休息一下吧。", exPy: "Wǒmen xiūxi yíxià ba.", exEn: "Let's take a break." },
  { id: 271, hz: "雪",     py: "xuě",       en: "snow",                           cat: "nature",     ex: "昨天下雪了。", exPy: "Zuótiān xiàxuě le.", exEn: "It snowed yesterday." },
  { id: 272, hz: "颜色",   py: "yánsè",     en: "color",                          cat: "misc",       ex: "你喜欢什么颜色？", exPy: "Nǐ xǐhuan shénme yánsè?", exEn: "What color do you like?" },
  { id: 273, hz: "眼睛",   py: "yǎnjing",   en: "eye",                            cat: "body",       ex: "她的眼睛很大。", exPy: "Tā de yǎnjing hěn dà.", exEn: "Her eyes are big." },
  { id: 274, hz: "羊肉",   py: "yángròu",   en: "mutton, lamb",                   cat: "food",       ex: "我不吃羊肉。", exPy: "Wǒ bù chī yángròu.", exEn: "I don't eat lamb." },
  { id: 275, hz: "药",     py: "yào",       en: "medicine",                       cat: "body",       ex: "你要吃药。", exPy: "Nǐ yào chī yào.", exEn: "You need to take medicine." },
  { id: 276, hz: "要",     py: "yào",       en: "to want; will; must",            cat: "verbs",      ex: "我要一杯咖啡。", exPy: "Wǒ yào yì bēi kāfēi.", exEn: "I want a cup of coffee." },
  { id: 277, hz: "也",     py: "yě",        en: "also, too",                      cat: "adverbs",    ex: "我也是学生。", exPy: "Wǒ yě shì xuésheng.", exEn: "I am also a student." },
  { id: 278, hz: "一起",   py: "yìqǐ",      en: "together",                       cat: "adverbs",    ex: "我们一起去吧。", exPy: "Wǒmen yìqǐ qù ba.", exEn: "Let's go together." },
  { id: 279, hz: "一下",   py: "yíxià",     en: "a bit, briefly (after a verb)",  cat: "measure",    ex: "请等一下。", exPy: "Qǐng děng yíxià.", exEn: "Please wait a moment." },
  { id: 280, hz: "已经",   py: "yǐjing",    en: "already",                        cat: "adverbs",    ex: "他已经走了。", exPy: "Tā yǐjing zǒu le.", exEn: "He has already left." },
  { id: 281, hz: "意思",   py: "yìsi",      en: "meaning",                        cat: "misc",       ex: "这个字是什么意思？", exPy: "Zhège zì shì shénme yìsi?", exEn: "What does this character mean?" },
  { id: 282, hz: "因为",   py: "yīnwèi",    en: "because",                        cat: "adverbs",    ex: "因为下雨，所以我没去。", exPy: "Yīnwèi xiàyǔ, suǒyǐ wǒ méi qù.", exEn: "Because it rained, I didn't go." },
  { id: 283, hz: "所以",   py: "suǒyǐ",     en: "so, therefore",                  cat: "adverbs",    ex: "我病了，所以没上班。", exPy: "Wǒ bìng le, suǒyǐ méi shàngbān.", exEn: "I was sick, so I didn't go to work." },
  { id: 284, hz: "阴",     py: "yīn",       en: "cloudy, overcast",               cat: "nature",     ex: "今天是阴天。", exPy: "Jīntiān shì yīntiān.", exEn: "It's cloudy today." },
  { id: 285, hz: "游泳",   py: "yóuyǒng",   en: "to swim",                        cat: "sports",     ex: "我会游泳。", exPy: "Wǒ huì yóuyǒng.", exEn: "I can swim." },
  { id: 286, hz: "右边",   py: "yòubian",   en: "right side",                     cat: "places",     ex: "商店在右边。", exPy: "Shāngdiàn zài yòubian.", exEn: "The shop is on the right." },
  { id: 287, hz: "鱼",     py: "yú",        en: "fish",                           cat: "animals",    ex: "我喜欢吃鱼。", exPy: "Wǒ xǐhuan chī yú.", exEn: "I like eating fish." },
  { id: 288, hz: "远",     py: "yuǎn",      en: "far",                            cat: "adjectives", ex: "机场很远。", exPy: "Jīchǎng hěn yuǎn.", exEn: "The airport is far away." },
  { id: 289, hz: "运动",   py: "yùndòng",   en: "sports, exercise",               cat: "sports",     ex: "我每天运动一小时。", exPy: "Wǒ měi tiān yùndòng yì xiǎoshí.", exEn: "I exercise one hour every day." },
  { id: 290, hz: "再",     py: "zài",       en: "again, once more",               cat: "adverbs",    ex: "请再说一次。", exPy: "Qǐng zài shuō yí cì.", exEn: "Please say it again." },
  { id: 291, hz: "早上",   py: "zǎoshang",  en: "morning",                        cat: "time",       ex: "早上好！", exPy: "Zǎoshang hǎo!", exEn: "Good morning!" },
  { id: 292, hz: "丈夫",   py: "zhàngfu",   en: "husband",                        cat: "family",     ex: "她的丈夫是医生。", exPy: "Tā de zhàngfu shì yīshēng.", exEn: "Her husband is a doctor." },
  { id: 293, hz: "找",     py: "zhǎo",      en: "to look for, to find",           cat: "verbs",      ex: "你在找什么？", exPy: "Nǐ zài zhǎo shénme?", exEn: "What are you looking for?" },
  { id: 294, hz: "着",     py: "zhe",       en: "(particle: ongoing state, -ing)", cat: "particles", ex: "门开着。", exPy: "Mén kāizhe.", exEn: "The door is open." },
  { id: 295, hz: "真",     py: "zhēn",      en: "really; true",                   cat: "adverbs",    ex: "这里真漂亮！", exPy: "Zhèlǐ zhēn piàoliang!", exEn: "It's really beautiful here!" },
  { id: 296, hz: "正在",   py: "zhèngzài",  en: "in the process of, currently",   cat: "adverbs",    ex: "我正在吃饭。", exPy: "Wǒ zhèngzài chīfàn.", exEn: "I am eating right now." },
  { id: 297, hz: "知道",   py: "zhīdao",    en: "to know",                        cat: "verbs",      ex: "我不知道。", exPy: "Wǒ bù zhīdao.", exEn: "I don't know." },
  { id: 298, hz: "准备",   py: "zhǔnbèi",   en: "to prepare; to plan to",         cat: "verbs",      ex: "我准备去中国。", exPy: "Wǒ zhǔnbèi qù Zhōngguó.", exEn: "I plan to go to China." },
  { id: 299, hz: "走",     py: "zǒu",       en: "to walk, to leave",              cat: "verbs",      ex: "我们走吧。", exPy: "Wǒmen zǒu ba.", exEn: "Let's go." },
  { id: 300, hz: "最",     py: "zuì",       en: "most, -est",                     cat: "adverbs",    ex: "我最喜欢夏天。", exPy: "Wǒ zuì xǐhuan xiàtiān.", exEn: "I like summer the most." },
  { id: 301, hz: "左边",   py: "zuǒbian",   en: "left side",                      cat: "places",     ex: "银行在左边。", exPy: "Yínháng zài zuǒbian.", exEn: "The bank is on the left." }
];
