/* HSK 3 vocabulary — 300 words (HSK 2.0 standard list, 2012).
 * Word list and pinyin follow the official list (via github.com/glxxyz/hskhsk.com, MIT).
 * Fields: id, hz (hanzi), py (pinyin), en, cat, ex (example), exPy, exEn
 */
window.HSK3_WORDS = [
  { id: 302, hz: "阿姨",   py: "āyí",       en: "aunt; auntie (any older woman)", cat: "family",     ex: "阿姨，您好！", exPy: "Āyí, nín hǎo!", exEn: "Hello, auntie!" },
  { id: 303, hz: "啊",     py: "a",         en: "(particle: exclamation, surprise)", cat: "particles", ex: "真漂亮啊！", exPy: "Zhēn piàoliang a!", exEn: "How beautiful!" },
  { id: 304, hz: "矮",     py: "ǎi",        en: "short (height), low",            cat: "adjectives", ex: "他比我矮。", exPy: "Tā bǐ wǒ ǎi.", exEn: "He is shorter than me." },
  { id: 305, hz: "爱好",   py: "àihào",     en: "hobby",                          cat: "sports",     ex: "你有什么爱好？", exPy: "Nǐ yǒu shénme àihào?", exEn: "What hobbies do you have?" },
  { id: 306, hz: "安静",   py: "ānjìng",    en: "quiet",                          cat: "adjectives", ex: "请安静一点儿。", exPy: "Qǐng ānjìng yìdiǎnr.", exEn: "Please be a little quieter." },
  { id: 307, hz: "把",     py: "bǎ",        en: "(particle: moves object before verb); measure word for handles", cat: "particles", ex: "请把门关上。", exPy: "Qǐng bǎ mén guānshàng.", exEn: "Please close the door." },
  { id: 308, hz: "班",     py: "bān",       en: "class (group); shift",           cat: "study",      ex: "我们班有二十个学生。", exPy: "Wǒmen bān yǒu èrshí gè xuésheng.", exEn: "Our class has twenty students." },
  { id: 309, hz: "搬",     py: "bān",       en: "to move (house, objects)",       cat: "verbs",      ex: "我们下个月搬家。", exPy: "Wǒmen xià gè yuè bānjiā.", exEn: "We are moving next month." },
  { id: 310, hz: "办法",   py: "bànfǎ",     en: "way, method",                    cat: "misc",       ex: "我有一个好办法。", exPy: "Wǒ yǒu yí gè hǎo bànfǎ.", exEn: "I have a good idea." },
  { id: 311, hz: "办公室", py: "bàngōngshì", en: "office",                        cat: "places",     ex: "经理在办公室。", exPy: "Jīnglǐ zài bàngōngshì.", exEn: "The manager is in the office." },
  { id: 312, hz: "半",     py: "bàn",       en: "half",                           cat: "numbers",    ex: "现在三点半。", exPy: "Xiànzài sān diǎn bàn.", exEn: "It's half past three." },
  { id: 313, hz: "帮忙",   py: "bāngmáng",  en: "to help out",                    cat: "verbs",      ex: "你能帮忙吗？", exPy: "Nǐ néng bāngmáng ma?", exEn: "Can you help?" },
  { id: 314, hz: "包",     py: "bāo",       en: "bag; to wrap",                   cat: "objects",    ex: "这个包很贵。", exPy: "Zhège bāo hěn guì.", exEn: "This bag is expensive." },
  { id: 315, hz: "饱",     py: "bǎo",       en: "full (after eating)",            cat: "adjectives", ex: "我吃饱了。", exPy: "Wǒ chī bǎo le.", exEn: "I'm full." },
  { id: 316, hz: "北方",   py: "běifāng",   en: "the north",                      cat: "places",     ex: "北方的冬天很冷。", exPy: "Běifāng de dōngtiān hěn lěng.", exEn: "Winter in the north is very cold." },
  { id: 317, hz: "被",     py: "bèi",       en: "by (passive marker)",            cat: "particles",  ex: "我的手机被偷了。", exPy: "Wǒ de shǒujī bèi tōu le.", exEn: "My phone was stolen." },
  { id: 318, hz: "鼻子",   py: "bízi",      en: "nose",                           cat: "body",       ex: "他的鼻子很高。", exPy: "Tā de bízi hěn gāo.", exEn: "He has a high nose." },
  { id: 319, hz: "比较",   py: "bǐjiào",    en: "relatively; to compare",         cat: "adverbs",    ex: "今天比较冷。", exPy: "Jīntiān bǐjiào lěng.", exEn: "It's relatively cold today." },
  { id: 320, hz: "比赛",   py: "bǐsài",     en: "match, competition",             cat: "sports",     ex: "明天有足球比赛。", exPy: "Míngtiān yǒu zúqiú bǐsài.", exEn: "There's a football match tomorrow." },
  { id: 321, hz: "笔记本", py: "bǐjìběn",   en: "notebook; laptop",               cat: "objects",    ex: "我的笔记本在桌子上。", exPy: "Wǒ de bǐjìběn zài zhuōzi shàng.", exEn: "My notebook is on the table." },
  { id: 322, hz: "必须",   py: "bìxū",      en: "must, have to",                  cat: "adverbs",    ex: "你必须去。", exPy: "Nǐ bìxū qù.", exEn: "You must go." },
  { id: 323, hz: "变化",   py: "biànhuà",   en: "change",                         cat: "misc",       ex: "这个城市变化很大。", exPy: "Zhège chéngshì biànhuà hěn dà.", exEn: "This city has changed a lot." },
  { id: 324, hz: "别人",   py: "biéren",    en: "other people",                   cat: "pronouns",   ex: "别人都走了。", exPy: "Biéren dōu zǒu le.", exEn: "Everyone else has left." },
  { id: 325, hz: "冰箱",   py: "bīngxiāng", en: "refrigerator",                   cat: "objects",    ex: "牛奶在冰箱里。", exPy: "Niúnǎi zài bīngxiāng lǐ.", exEn: "The milk is in the fridge." },
  { id: 326, hz: "不但",   py: "búdàn",     en: "not only",                       cat: "adverbs",    ex: "她不但漂亮，而且聪明。", exPy: "Tā búdàn piàoliang, érqiě cōngming.", exEn: "She is not only pretty but also smart." },
  { id: 327, hz: "而且",   py: "érqiě",     en: "moreover, and also",             cat: "adverbs",    ex: "这个菜好吃，而且便宜。", exPy: "Zhège cài hǎochī, érqiě piányi.", exEn: "This dish is tasty and also cheap." },
  { id: 328, hz: "菜单",   py: "càidān",    en: "menu",                           cat: "food",       ex: "请给我菜单。", exPy: "Qǐng gěi wǒ càidān.", exEn: "Please give me the menu." },
  { id: 329, hz: "参加",   py: "cānjiā",    en: "to take part in",                cat: "verbs",      ex: "我想参加比赛。", exPy: "Wǒ xiǎng cānjiā bǐsài.", exEn: "I want to take part in the competition." },
  { id: 330, hz: "草",     py: "cǎo",       en: "grass",                          cat: "nature",     ex: "草是绿色的。", exPy: "Cǎo shì lǜsè de.", exEn: "Grass is green." },
  { id: 331, hz: "层",     py: "céng",      en: "floor, layer (measure word)",    cat: "measure",    ex: "我住在五层。", exPy: "Wǒ zhù zài wǔ céng.", exEn: "I live on the fifth floor." },
  { id: 332, hz: "差",     py: "chà",       en: "poor, bad; to lack; short of",   cat: "adjectives", ex: "现在差五分八点。", exPy: "Xiànzài chà wǔ fēn bā diǎn.", exEn: "It's five to eight." },
  { id: 333, hz: "超市",   py: "chāoshì",   en: "supermarket",                    cat: "places",     ex: "我去超市买东西。", exPy: "Wǒ qù chāoshì mǎi dōngxi.", exEn: "I'm going to the supermarket to shop." },
  { id: 334, hz: "衬衫",   py: "chènshān",  en: "shirt",                          cat: "objects",    ex: "这件衬衫很好看。", exPy: "Zhè jiàn chènshān hěn hǎokàn.", exEn: "This shirt looks nice." },
  { id: 335, hz: "成绩",   py: "chéngjì",   en: "grade, result",                  cat: "study",      ex: "他的成绩很好。", exPy: "Tā de chéngjì hěn hǎo.", exEn: "His grades are very good." },
  { id: 336, hz: "城市",   py: "chéngshì",  en: "city",                           cat: "places",     ex: "北京是一个大城市。", exPy: "Běijīng shì yí gè dà chéngshì.", exEn: "Beijing is a big city." },
  { id: 337, hz: "迟到",   py: "chídào",    en: "to be late",                     cat: "verbs",      ex: "对不起，我迟到了。", exPy: "Duìbuqǐ, wǒ chídào le.", exEn: "Sorry, I'm late." },
  { id: 338, hz: "除了",   py: "chúle",     en: "except; besides",                cat: "particles",  ex: "除了他，大家都来了。", exPy: "Chúle tā, dàjiā dōu lái le.", exEn: "Everyone came except him." },
  { id: 339, hz: "船",     py: "chuán",     en: "boat, ship",                     cat: "transport",  ex: "我们坐船去。", exPy: "Wǒmen zuò chuán qù.", exEn: "We go by boat." },
  { id: 340, hz: "春",     py: "chūn",      en: "spring (season)",                cat: "time",       ex: "春天来了。", exPy: "Chūntiān lái le.", exEn: "Spring has come." },
  { id: 341, hz: "词典",   py: "cídiǎn",    en: "dictionary",                     cat: "study",      ex: "我用词典查这个词。", exPy: "Wǒ yòng cídiǎn chá zhège cí.", exEn: "I look up this word in the dictionary." },
  { id: 342, hz: "聪明",   py: "cōngming",  en: "clever, smart",                  cat: "adjectives", ex: "这个孩子很聪明。", exPy: "Zhège háizi hěn cōngming.", exEn: "This child is very smart." },
  { id: 343, hz: "打扫",   py: "dǎsǎo",     en: "to clean, to sweep",             cat: "verbs",      ex: "我周末打扫房间。", exPy: "Wǒ zhōumò dǎsǎo fángjiān.", exEn: "I clean my room on weekends." },
  { id: 344, hz: "打算",   py: "dǎsuàn",    en: "to plan, to intend",             cat: "verbs",      ex: "你打算做什么？", exPy: "Nǐ dǎsuàn zuò shénme?", exEn: "What do you plan to do?" },
  { id: 345, hz: "带",     py: "dài",       en: "to bring, to carry; belt",       cat: "verbs",      ex: "别忘了带护照。", exPy: "Bié wàng le dài hùzhào.", exEn: "Don't forget to bring your passport." },
  { id: 346, hz: "担心",   py: "dānxīn",    en: "to worry",                       cat: "verbs",      ex: "别担心，没问题。", exPy: "Bié dānxīn, méi wèntí.", exEn: "Don't worry, no problem." },
  { id: 347, hz: "蛋糕",   py: "dàngāo",    en: "cake",                           cat: "food",       ex: "生日蛋糕很好吃。", exPy: "Shēngrì dàngāo hěn hǎochī.", exEn: "The birthday cake is delicious." },
  { id: 348, hz: "当然",   py: "dāngrán",   en: "of course",                      cat: "adverbs",    ex: "当然可以！", exPy: "Dāngrán kěyǐ!", exEn: "Of course you can!" },
  { id: 349, hz: "地",     py: "de",        en: "(adverbial particle: -ly)",      cat: "particles",  ex: "他慢慢地走。", exPy: "Tā mànmàn de zǒu.", exEn: "He walks slowly." },
  { id: 350, hz: "灯",     py: "dēng",      en: "lamp, light",                    cat: "objects",    ex: "请开灯。", exPy: "Qǐng kāi dēng.", exEn: "Please turn on the light." },
  { id: 351, hz: "地方",   py: "dìfang",    en: "place",                          cat: "places",     ex: "这个地方很漂亮。", exPy: "Zhège dìfang hěn piàoliang.", exEn: "This place is very beautiful." },
  { id: 352, hz: "地铁",   py: "dìtiě",     en: "subway, metro",                  cat: "transport",  ex: "我坐地铁上班。", exPy: "Wǒ zuò dìtiě shàngbān.", exEn: "I take the subway to work." },
  { id: 353, hz: "地图",   py: "dìtú",      en: "map",                            cat: "objects",    ex: "我看地图找路。", exPy: "Wǒ kàn dìtú zhǎo lù.", exEn: "I look at the map to find the way." },
  { id: 354, hz: "电梯",   py: "diàntī",    en: "elevator",                       cat: "objects",    ex: "电梯在那边。", exPy: "Diàntī zài nàbiān.", exEn: "The elevator is over there." },
  { id: 355, hz: "电子邮件", py: "diànzǐ yóujiàn", en: "email",                   cat: "objects",    ex: "请给我发电子邮件。", exPy: "Qǐng gěi wǒ fā diànzǐ yóujiàn.", exEn: "Please send me an email." },
  { id: 356, hz: "东",     py: "dōng",      en: "east",                           cat: "places",     ex: "太阳从东边出来。", exPy: "Tàiyáng cóng dōngbian chūlái.", exEn: "The sun rises in the east." },
  { id: 357, hz: "冬",     py: "dōng",      en: "winter",                         cat: "time",       ex: "冬天很冷。", exPy: "Dōngtiān hěn lěng.", exEn: "Winter is very cold." },
  { id: 358, hz: "动物",   py: "dòngwù",    en: "animal",                         cat: "animals",    ex: "我喜欢小动物。", exPy: "Wǒ xǐhuan xiǎo dòngwù.", exEn: "I like small animals." },
  { id: 359, hz: "短",     py: "duǎn",      en: "short (length, time)",           cat: "adjectives", ex: "她的头发很短。", exPy: "Tā de tóufa hěn duǎn.", exEn: "Her hair is very short." },
  { id: 360, hz: "段",     py: "duàn",      en: "section, paragraph (measure word)", cat: "measure", ex: "请读这段话。", exPy: "Qǐng dú zhè duàn huà.", exEn: "Please read this paragraph." },
  { id: 361, hz: "锻炼",   py: "duànliàn",  en: "to exercise, to work out",       cat: "sports",     ex: "我每天早上锻炼。", exPy: "Wǒ měi tiān zǎoshang duànliàn.", exEn: "I exercise every morning." },
  { id: 362, hz: "多么",   py: "duōme",     en: "how (exclamation)",              cat: "adverbs",    ex: "多么漂亮的花！", exPy: "Duōme piàoliang de huā!", exEn: "What beautiful flowers!" },
  { id: 363, hz: "饿",     py: "è",         en: "hungry",                         cat: "adjectives", ex: "我饿了。", exPy: "Wǒ è le.", exEn: "I'm hungry." },
  { id: 364, hz: "耳朵",   py: "ěrduo",     en: "ear",                            cat: "body",       ex: "兔子的耳朵很长。", exPy: "Tùzi de ěrduo hěn cháng.", exEn: "Rabbits have long ears." },
  { id: 365, hz: "发",     py: "fā",        en: "to send; to issue",              cat: "verbs",      ex: "我给你发短信。", exPy: "Wǒ gěi nǐ fā duǎnxìn.", exEn: "I'll send you a text message." },
  { id: 366, hz: "发烧",   py: "fāshāo",    en: "to have a fever",                cat: "body",       ex: "他发烧了。", exPy: "Tā fāshāo le.", exEn: "He has a fever." },
  { id: 367, hz: "发现",   py: "fāxiàn",    en: "to discover, to find",           cat: "verbs",      ex: "我发现了一个问题。", exPy: "Wǒ fāxiàn le yí gè wèntí.", exEn: "I found a problem." },
  { id: 368, hz: "方便",   py: "fāngbiàn",  en: "convenient",                     cat: "adjectives", ex: "坐地铁很方便。", exPy: "Zuò dìtiě hěn fāngbiàn.", exEn: "Taking the subway is convenient." },
  { id: 369, hz: "放",     py: "fàng",      en: "to put, to place",               cat: "verbs",      ex: "把书放在桌子上。", exPy: "Bǎ shū fàng zài zhuōzi shàng.", exEn: "Put the book on the table." },
  { id: 370, hz: "放心",   py: "fàngxīn",   en: "to feel relieved, not worry",    cat: "verbs",      ex: "你放心，我会帮你。", exPy: "Nǐ fàngxīn, wǒ huì bāng nǐ.", exEn: "Don't worry, I'll help you." },
  { id: 371, hz: "分",     py: "fēn",       en: "minute; cent; to divide",        cat: "time",       ex: "现在八点十分。", exPy: "Xiànzài bā diǎn shí fēn.", exEn: "It's 8:10 now." },
  { id: 372, hz: "附近",   py: "fùjìn",     en: "nearby, vicinity",               cat: "places",     ex: "附近有超市吗？", exPy: "Fùjìn yǒu chāoshì ma?", exEn: "Is there a supermarket nearby?" },
  { id: 373, hz: "复习",   py: "fùxí",      en: "to review (studies)",            cat: "study",      ex: "我在复习汉语。", exPy: "Wǒ zài fùxí Hànyǔ.", exEn: "I'm reviewing Chinese." },
  { id: 374, hz: "干净",   py: "gānjìng",   en: "clean",                          cat: "adjectives", ex: "房间很干净。", exPy: "Fángjiān hěn gānjìng.", exEn: "The room is very clean." },
  { id: 375, hz: "感冒",   py: "gǎnmào",    en: "to catch a cold; cold",          cat: "body",       ex: "我感冒了。", exPy: "Wǒ gǎnmào le.", exEn: "I have a cold." },
  { id: 376, hz: "感兴趣", py: "gǎn xìngqù", en: "to be interested in",           cat: "verbs",      ex: "我对历史感兴趣。", exPy: "Wǒ duì lìshǐ gǎn xìngqù.", exEn: "I'm interested in history." },
  { id: 377, hz: "刚才",   py: "gāngcái",   en: "just now",                       cat: "time",       ex: "他刚才还在这儿。", exPy: "Tā gāngcái hái zài zhèr.", exEn: "He was here just now." },
  { id: 378, hz: "个子",   py: "gèzi",      en: "height, build",                  cat: "body",       ex: "他个子很高。", exPy: "Tā gèzi hěn gāo.", exEn: "He is tall." },
  { id: 379, hz: "根据",   py: "gēnjù",     en: "according to",                   cat: "particles",  ex: "根据天气预报，明天下雨。", exPy: "Gēnjù tiānqì yùbào, míngtiān xiàyǔ.", exEn: "According to the forecast, it rains tomorrow." },
  { id: 380, hz: "跟",     py: "gēn",       en: "with; to follow",                cat: "particles",  ex: "我跟你一起去。", exPy: "Wǒ gēn nǐ yìqǐ qù.", exEn: "I'll go with you." },
  { id: 381, hz: "更",     py: "gèng",      en: "even more",                      cat: "adverbs",    ex: "今天比昨天更冷。", exPy: "Jīntiān bǐ zuótiān gèng lěng.", exEn: "Today is even colder than yesterday." },
  { id: 382, hz: "公斤",   py: "gōngjīn",   en: "kilogram",                       cat: "measure",    ex: "我买了两公斤苹果。", exPy: "Wǒ mǎi le liǎng gōngjīn píngguǒ.", exEn: "I bought two kilos of apples." },
  { id: 383, hz: "公园",   py: "gōngyuán",  en: "park",                           cat: "places",     ex: "我们去公园散步。", exPy: "Wǒmen qù gōngyuán sànbù.", exEn: "We go for a walk in the park." },
  { id: 384, hz: "故事",   py: "gùshi",     en: "story",                          cat: "misc",       ex: "妈妈给我讲故事。", exPy: "Māma gěi wǒ jiǎng gùshi.", exEn: "Mom tells me a story." },
  { id: 385, hz: "刮风",   py: "guāfēng",   en: "to be windy",                    cat: "nature",     ex: "今天刮风了。", exPy: "Jīntiān guāfēng le.", exEn: "It's windy today." },
  { id: 386, hz: "关",     py: "guān",      en: "to close, to turn off",          cat: "verbs",      ex: "请关灯。", exPy: "Qǐng guān dēng.", exEn: "Please turn off the light." },
  { id: 387, hz: "关系",   py: "guānxi",    en: "relationship, relation",         cat: "misc",       ex: "他们关系很好。", exPy: "Tāmen guānxi hěn hǎo.", exEn: "They have a good relationship." },
  { id: 388, hz: "关心",   py: "guānxīn",   en: "to care about",                  cat: "verbs",      ex: "妈妈很关心我。", exPy: "Māma hěn guānxīn wǒ.", exEn: "Mom cares about me a lot." },
  { id: 389, hz: "关于",   py: "guānyú",    en: "about, regarding",               cat: "particles",  ex: "这是关于中国的书。", exPy: "Zhè shì guānyú Zhōngguó de shū.", exEn: "This is a book about China." },
  { id: 390, hz: "国家",   py: "guójiā",    en: "country, nation",                cat: "places",     ex: "中国是一个大国家。", exPy: "Zhōngguó shì yí gè dà guójiā.", exEn: "China is a big country." },
  { id: 391, hz: "过",     py: "guo",       en: "(particle: past experience, have ever)", cat: "particles", ex: "我去过中国。", exPy: "Wǒ qùguo Zhōngguó.", exEn: "I have been to China." },
  { id: 392, hz: "过去",   py: "guòqù",     en: "the past; to go over",           cat: "time",       ex: "过去这里是学校。", exPy: "Guòqù zhèlǐ shì xuéxiào.", exEn: "In the past this was a school." },
  { id: 393, hz: "还是",   py: "háishi",    en: "or (in questions); still; had better", cat: "adverbs", ex: "你喝茶还是咖啡？", exPy: "Nǐ hē chá háishi kāfēi?", exEn: "Do you drink tea or coffee?" },
  { id: 394, hz: "害怕",   py: "hàipà",     en: "to be afraid",                   cat: "verbs",      ex: "我害怕狗。", exPy: "Wǒ hàipà gǒu.", exEn: "I'm afraid of dogs." },
  { id: 395, hz: "黑板",   py: "hēibǎn",    en: "blackboard",                     cat: "study",      ex: "老师在黑板上写字。", exPy: "Lǎoshī zài hēibǎn shàng xiě zì.", exEn: "The teacher writes on the blackboard." },
  { id: 396, hz: "后来",   py: "hòulái",    en: "later, afterwards",              cat: "time",       ex: "后来他去了北京。", exPy: "Hòulái tā qù le Běijīng.", exEn: "Later he went to Beijing." },
  { id: 397, hz: "护照",   py: "hùzhào",    en: "passport",                       cat: "objects",    ex: "请出示您的护照。", exPy: "Qǐng chūshì nín de hùzhào.", exEn: "Please show your passport." },
  { id: 398, hz: "花",     py: "huā",       en: "flower; to spend",               cat: "nature",     ex: "这些花真漂亮。", exPy: "Zhèxiē huā zhēn piàoliang.", exEn: "These flowers are really beautiful." },
  { id: 399, hz: "画",     py: "huà",       en: "to draw, to paint; painting",    cat: "sports",     ex: "她喜欢画画。", exPy: "Tā xǐhuan huàhuà.", exEn: "She likes drawing." },
  { id: 400, hz: "坏",     py: "huài",      en: "bad; broken",                    cat: "adjectives", ex: "我的手机坏了。", exPy: "Wǒ de shǒujī huài le.", exEn: "My phone is broken." },
  { id: 401, hz: "欢迎",   py: "huānyíng",  en: "to welcome",                     cat: "phrases",    ex: "欢迎来到北京！", exPy: "Huānyíng lái dào Běijīng!", exEn: "Welcome to Beijing!" },
  { id: 402, hz: "还",     py: "huán",      en: "to return, to give back",        cat: "verbs",      ex: "我明天还你书。", exPy: "Wǒ míngtiān huán nǐ shū.", exEn: "I'll return your book tomorrow." },
  { id: 403, hz: "环境",   py: "huánjìng",  en: "environment, surroundings",      cat: "nature",     ex: "这里环境很好。", exPy: "Zhèlǐ huánjìng hěn hǎo.", exEn: "The environment here is very good." },
  { id: 404, hz: "换",     py: "huàn",      en: "to change, to exchange",         cat: "verbs",      ex: "我想换钱。", exPy: "Wǒ xiǎng huàn qián.", exEn: "I'd like to exchange money." },
  { id: 405, hz: "黄河",   py: "Huánghé",   en: "the Yellow River",               cat: "places",     ex: "黄河很长。", exPy: "Huánghé hěn cháng.", exEn: "The Yellow River is very long." },
  { id: 406, hz: "回答",   py: "huídá",     en: "to answer",                      cat: "verbs",      ex: "请回答我的问题。", exPy: "Qǐng huídá wǒ de wèntí.", exEn: "Please answer my question." },
  { id: 407, hz: "会议",   py: "huìyì",     en: "meeting, conference",            cat: "study",      ex: "下午有一个会议。", exPy: "Xiàwǔ yǒu yí gè huìyì.", exEn: "There's a meeting in the afternoon." },
  { id: 408, hz: "或者",   py: "huòzhě",    en: "or (in statements)",             cat: "adverbs",    ex: "你或者他去都可以。", exPy: "Nǐ huòzhě tā qù dōu kěyǐ.", exEn: "Either you or he can go." },
  { id: 409, hz: "几乎",   py: "jīhū",      en: "almost",                         cat: "adverbs",    ex: "我几乎每天都跑步。", exPy: "Wǒ jīhū měi tiān dōu pǎobù.", exEn: "I run almost every day." },
  { id: 410, hz: "机会",   py: "jīhuì",     en: "opportunity, chance",            cat: "misc",       ex: "这是一个好机会。", exPy: "Zhè shì yí gè hǎo jīhuì.", exEn: "This is a good opportunity." },
  { id: 411, hz: "极",     py: "jí",        en: "extremely",                      cat: "adverbs",    ex: "这个菜好吃极了。", exPy: "Zhège cài hǎochī jí le.", exEn: "This dish is extremely tasty." },
  { id: 412, hz: "记得",   py: "jìde",      en: "to remember",                    cat: "verbs",      ex: "我记得他的名字。", exPy: "Wǒ jìde tā de míngzi.", exEn: "I remember his name." },
  { id: 413, hz: "季节",   py: "jìjié",     en: "season",                         cat: "time",       ex: "你最喜欢哪个季节？", exPy: "Nǐ zuì xǐhuan nǎge jìjié?", exEn: "Which season do you like best?" },
  { id: 414, hz: "检查",   py: "jiǎnchá",   en: "to check, to examine",           cat: "verbs",      ex: "医生给我检查身体。", exPy: "Yīshēng gěi wǒ jiǎnchá shēntǐ.", exEn: "The doctor gives me a check-up." },
  { id: 415, hz: "简单",   py: "jiǎndān",   en: "simple, easy",                   cat: "adjectives", ex: "这个问题很简单。", exPy: "Zhège wèntí hěn jiǎndān.", exEn: "This question is very simple." },
  { id: 416, hz: "见面",   py: "jiànmiàn",  en: "to meet (someone)",              cat: "verbs",      ex: "我们明天见面。", exPy: "Wǒmen míngtiān jiànmiàn.", exEn: "We'll meet tomorrow." },
  { id: 417, hz: "健康",   py: "jiànkāng",  en: "healthy; health",                cat: "body",       ex: "祝你健康！", exPy: "Zhù nǐ jiànkāng!", exEn: "Wishing you good health!" },
  { id: 418, hz: "讲",     py: "jiǎng",     en: "to speak, to explain, to tell",  cat: "verbs",      ex: "老师讲得很清楚。", exPy: "Lǎoshī jiǎng de hěn qīngchu.", exEn: "The teacher explains very clearly." },
  { id: 419, hz: "教",     py: "jiāo",      en: "to teach",                       cat: "study",      ex: "他教我们汉语。", exPy: "Tā jiāo wǒmen Hànyǔ.", exEn: "He teaches us Chinese." },
  { id: 420, hz: "角",     py: "jiǎo",      en: "jiao (0.1 yuan); corner; horn",  cat: "measure",    ex: "这个五角。", exPy: "Zhège wǔ jiǎo.", exEn: "This costs five jiao." },
  { id: 421, hz: "脚",     py: "jiǎo",      en: "foot",                           cat: "body",       ex: "我的脚很疼。", exPy: "Wǒ de jiǎo hěn téng.", exEn: "My foot hurts." },
  { id: 422, hz: "接",     py: "jiē",       en: "to pick up (someone); to receive; to answer (phone)", cat: "verbs", ex: "我去机场接你。", exPy: "Wǒ qù jīchǎng jiē nǐ.", exEn: "I'll pick you up at the airport." },
  { id: 423, hz: "街道",   py: "jiēdào",    en: "street",                         cat: "places",     ex: "这条街道很安静。", exPy: "Zhè tiáo jiēdào hěn ānjìng.", exEn: "This street is very quiet." },
  { id: 424, hz: "节目",   py: "jiémù",     en: "program, show",                  cat: "misc",       ex: "这个节目很有意思。", exPy: "Zhège jiémù hěn yǒu yìsi.", exEn: "This show is very interesting." },
  { id: 425, hz: "节日",   py: "jiérì",     en: "festival, holiday",              cat: "time",       ex: "春节是中国最重要的节日。", exPy: "Chūnjié shì Zhōngguó zuì zhòngyào de jiérì.", exEn: "Spring Festival is China's most important holiday." },
  { id: 426, hz: "结婚",   py: "jiéhūn",    en: "to get married",                 cat: "verbs",      ex: "他们去年结婚了。", exPy: "Tāmen qùnián jiéhūn le.", exEn: "They got married last year." },
  { id: 427, hz: "结束",   py: "jiéshù",    en: "to end, to finish",              cat: "verbs",      ex: "会议结束了。", exPy: "Huìyì jiéshù le.", exEn: "The meeting is over." },
  { id: 428, hz: "解决",   py: "jiějué",    en: "to solve",                       cat: "verbs",      ex: "问题解决了。", exPy: "Wèntí jiějué le.", exEn: "The problem is solved." },
  { id: 429, hz: "借",     py: "jiè",       en: "to borrow, to lend",             cat: "verbs",      ex: "我可以借你的笔吗？", exPy: "Wǒ kěyǐ jiè nǐ de bǐ ma?", exEn: "May I borrow your pen?" },
  { id: 430, hz: "经常",   py: "jīngcháng", en: "often",                          cat: "adverbs",    ex: "我经常去图书馆。", exPy: "Wǒ jīngcháng qù túshūguǎn.", exEn: "I often go to the library." },
  { id: 431, hz: "经过",   py: "jīngguò",   en: "to pass by; through",            cat: "verbs",      ex: "我每天经过公园。", exPy: "Wǒ měi tiān jīngguò gōngyuán.", exEn: "I pass the park every day." },
  { id: 432, hz: "经理",   py: "jīnglǐ",    en: "manager",                        cat: "people",     ex: "他是我们的经理。", exPy: "Tā shì wǒmen de jīnglǐ.", exEn: "He is our manager." },
  { id: 433, hz: "久",     py: "jiǔ",       en: "long (time)",                    cat: "time",       ex: "好久不见！", exPy: "Hǎo jiǔ bú jiàn!", exEn: "Long time no see!" },
  { id: 434, hz: "旧",     py: "jiù",       en: "old (things), used",             cat: "adjectives", ex: "这是一本旧书。", exPy: "Zhè shì yì běn jiù shū.", exEn: "This is an old book." },
  { id: 435, hz: "句子",   py: "jùzi",      en: "sentence",                       cat: "study",      ex: "请读这个句子。", exPy: "Qǐng dú zhège jùzi.", exEn: "Please read this sentence." },
  { id: 436, hz: "决定",   py: "juédìng",   en: "to decide; decision",            cat: "verbs",      ex: "我决定去中国学习。", exPy: "Wǒ juédìng qù Zhōngguó xuéxí.", exEn: "I decided to study in China." },
  { id: 437, hz: "可爱",   py: "kě'ài",     en: "cute, lovely",                   cat: "adjectives", ex: "这只猫真可爱。", exPy: "Zhè zhī māo zhēn kě'ài.", exEn: "This cat is really cute." },
  { id: 438, hz: "渴",     py: "kě",        en: "thirsty",                        cat: "adjectives", ex: "我渴了，想喝水。", exPy: "Wǒ kě le, xiǎng hē shuǐ.", exEn: "I'm thirsty, I want to drink water." },
  { id: 439, hz: "刻",     py: "kè",        en: "quarter (of an hour)",           cat: "time",       ex: "现在三点一刻。", exPy: "Xiànzài sān diǎn yí kè.", exEn: "It's a quarter past three." },
  { id: 440, hz: "客人",   py: "kèrén",     en: "guest, customer",                cat: "people",     ex: "今天家里有客人。", exPy: "Jīntiān jiā lǐ yǒu kèrén.", exEn: "We have guests at home today." },
  { id: 441, hz: "空调",   py: "kōngtiáo",  en: "air conditioner",                cat: "objects",    ex: "请开空调。", exPy: "Qǐng kāi kōngtiáo.", exEn: "Please turn on the air conditioner." },
  { id: 442, hz: "口",     py: "kǒu",       en: "mouth; (measure word for family members)", cat: "body", ex: "我家有四口人。", exPy: "Wǒ jiā yǒu sì kǒu rén.", exEn: "There are four people in my family." },
  { id: 443, hz: "哭",     py: "kū",        en: "to cry",                         cat: "verbs",      ex: "孩子哭了。", exPy: "Háizi kū le.", exEn: "The child is crying." },
  { id: 444, hz: "裤子",   py: "kùzi",      en: "trousers, pants",                cat: "objects",    ex: "这条裤子太长了。", exPy: "Zhè tiáo kùzi tài cháng le.", exEn: "These trousers are too long." },
  { id: 445, hz: "筷子",   py: "kuàizi",    en: "chopsticks",                     cat: "objects",    ex: "你会用筷子吗？", exPy: "Nǐ huì yòng kuàizi ma?", exEn: "Can you use chopsticks?" },
  { id: 446, hz: "蓝",     py: "lán",       en: "blue",                           cat: "adjectives", ex: "天很蓝。", exPy: "Tiān hěn lán.", exEn: "The sky is very blue." },
  { id: 447, hz: "老",     py: "lǎo",       en: "old (people)",                   cat: "adjectives", ex: "我爷爷很老了。", exPy: "Wǒ yéye hěn lǎo le.", exEn: "My grandpa is very old." },
  { id: 448, hz: "离开",   py: "líkāi",     en: "to leave",                       cat: "verbs",      ex: "他已经离开了。", exPy: "Tā yǐjing líkāi le.", exEn: "He has already left." },
  { id: 449, hz: "礼物",   py: "lǐwù",      en: "gift, present",                  cat: "objects",    ex: "这是给你的礼物。", exPy: "Zhè shì gěi nǐ de lǐwù.", exEn: "This is a gift for you." },
  { id: 450, hz: "历史",   py: "lìshǐ",     en: "history",                        cat: "study",      ex: "我喜欢中国历史。", exPy: "Wǒ xǐhuan Zhōngguó lìshǐ.", exEn: "I like Chinese history." },
  { id: 451, hz: "脸",     py: "liǎn",      en: "face",                           cat: "body",       ex: "她的脸红了。", exPy: "Tā de liǎn hóng le.", exEn: "Her face turned red." },
  { id: 452, hz: "练习",   py: "liànxí",    en: "to practice; exercise",          cat: "study",      ex: "我每天练习写汉字。", exPy: "Wǒ měi tiān liànxí xiě Hànzì.", exEn: "I practice writing characters every day." },
  { id: 453, hz: "辆",     py: "liàng",     en: "(measure word for vehicles)",    cat: "measure",    ex: "他买了一辆新车。", exPy: "Tā mǎi le yí liàng xīn chē.", exEn: "He bought a new car." },
  { id: 454, hz: "聊天",   py: "liáotiān",  en: "to chat",                        cat: "verbs",      ex: "我们聊聊天吧。", exPy: "Wǒmen liáoliao tiān ba.", exEn: "Let's have a chat." },
  { id: 455, hz: "了解",   py: "liǎojiě",   en: "to understand, to know about",   cat: "verbs",      ex: "我很了解他。", exPy: "Wǒ hěn liǎojiě tā.", exEn: "I know him well." },
  { id: 456, hz: "邻居",   py: "línjū",     en: "neighbor",                       cat: "people",     ex: "我的邻居很热情。", exPy: "Wǒ de línjū hěn rèqíng.", exEn: "My neighbors are very warm-hearted." },
  { id: 457, hz: "留学",   py: "liúxué",    en: "to study abroad",                cat: "study",      ex: "他在中国留学。", exPy: "Tā zài Zhōngguó liúxué.", exEn: "He is studying abroad in China." },
  { id: 458, hz: "楼",     py: "lóu",       en: "building; floor",                cat: "places",     ex: "我住在三楼。", exPy: "Wǒ zhù zài sān lóu.", exEn: "I live on the third floor." },
  { id: 459, hz: "绿",     py: "lǜ",        en: "green",                          cat: "adjectives", ex: "树叶是绿色的。", exPy: "Shùyè shì lǜsè de.", exEn: "Leaves are green." },
  { id: 460, hz: "马",     py: "mǎ",        en: "horse",                          cat: "animals",    ex: "我会骑马。", exPy: "Wǒ huì qí mǎ.", exEn: "I can ride a horse." },
  { id: 461, hz: "马上",   py: "mǎshàng",   en: "right away, immediately",        cat: "adverbs",    ex: "我马上到。", exPy: "Wǒ mǎshàng dào.", exEn: "I'll be there right away." },
  { id: 462, hz: "满意",   py: "mǎnyì",     en: "satisfied",                      cat: "adjectives", ex: "我对这个工作很满意。", exPy: "Wǒ duì zhège gōngzuò hěn mǎnyì.", exEn: "I'm satisfied with this job." },
  { id: 463, hz: "帽子",   py: "màozi",     en: "hat, cap",                       cat: "objects",    ex: "他戴着一个帽子。", exPy: "Tā dàizhe yí gè màozi.", exEn: "He is wearing a hat." },
  { id: 464, hz: "米",     py: "mǐ",        en: "meter; rice (uncooked)",         cat: "measure",    ex: "他一米八。", exPy: "Tā yì mǐ bā.", exEn: "He is 1.80 m tall." },
  { id: 465, hz: "面包",   py: "miànbāo",   en: "bread",                          cat: "food",       ex: "我早上吃面包。", exPy: "Wǒ zǎoshang chī miànbāo.", exEn: "I eat bread in the morning." },
  { id: 466, hz: "明白",   py: "míngbai",   en: "to understand; clear",           cat: "verbs",      ex: "我明白了。", exPy: "Wǒ míngbai le.", exEn: "I understand." },
  { id: 467, hz: "拿",     py: "ná",        en: "to take, to hold",               cat: "verbs",      ex: "请拿好你的东西。", exPy: "Qǐng ná hǎo nǐ de dōngxi.", exEn: "Please hold on to your things." },
  { id: 468, hz: "奶奶",   py: "nǎinai",    en: "grandmother (father's side)",    cat: "family",     ex: "奶奶今年八十岁。", exPy: "Nǎinai jīnnián bāshí suì.", exEn: "Grandma is eighty this year." },
  { id: 469, hz: "南",     py: "nán",       en: "south",                          cat: "places",     ex: "他住在城市南边。", exPy: "Tā zhù zài chéngshì nánbian.", exEn: "He lives in the south of the city." },
  { id: 470, hz: "难",     py: "nán",       en: "difficult",                      cat: "adjectives", ex: "汉字很难写。", exPy: "Hànzì hěn nán xiě.", exEn: "Chinese characters are hard to write." },
  { id: 471, hz: "难过",   py: "nánguò",    en: "sad, upset",                     cat: "adjectives", ex: "别难过了。", exPy: "Bié nánguò le.", exEn: "Don't be sad." },
  { id: 472, hz: "年级",   py: "niánjí",    en: "grade, year (in school)",        cat: "study",      ex: "你几年级？", exPy: "Nǐ jǐ niánjí?", exEn: "What grade are you in?" },
  { id: 473, hz: "年轻",   py: "niánqīng",  en: "young",                          cat: "adjectives", ex: "他还很年轻。", exPy: "Tā hái hěn niánqīng.", exEn: "He is still very young." },
  { id: 474, hz: "鸟",     py: "niǎo",      en: "bird",                           cat: "animals",    ex: "树上有很多鸟。", exPy: "Shù shàng yǒu hěn duō niǎo.", exEn: "There are many birds in the tree." },
  { id: 475, hz: "努力",   py: "nǔlì",      en: "to work hard; hard-working",     cat: "verbs",      ex: "他学习很努力。", exPy: "Tā xuéxí hěn nǔlì.", exEn: "He studies very hard." },
  { id: 476, hz: "爬山",   py: "páshān",    en: "to climb a mountain, to hike",   cat: "sports",     ex: "周末我们去爬山。", exPy: "Zhōumò wǒmen qù páshān.", exEn: "We go hiking on the weekend." },
  { id: 477, hz: "盘子",   py: "pánzi",     en: "plate",                          cat: "objects",    ex: "盘子里有水果。", exPy: "Pánzi lǐ yǒu shuǐguǒ.", exEn: "There is fruit on the plate." },
  { id: 478, hz: "胖",     py: "pàng",      en: "fat, plump",                     cat: "adjectives", ex: "这只猫很胖。", exPy: "Zhè zhī māo hěn pàng.", exEn: "This cat is very fat." },
  { id: 479, hz: "皮鞋",   py: "píxié",     en: "leather shoes",                  cat: "objects",    ex: "他穿着黑皮鞋。", exPy: "Tā chuānzhe hēi píxié.", exEn: "He is wearing black leather shoes." },
  { id: 480, hz: "啤酒",   py: "píjiǔ",     en: "beer",                           cat: "food",       ex: "来两瓶啤酒。", exPy: "Lái liǎng píng píjiǔ.", exEn: "Two bottles of beer, please." },
  { id: 481, hz: "瓶子",   py: "píngzi",    en: "bottle",                         cat: "objects",    ex: "瓶子里没有水了。", exPy: "Píngzi lǐ méiyǒu shuǐ le.", exEn: "There is no water left in the bottle." },
  { id: 482, hz: "其实",   py: "qíshí",     en: "actually, in fact",              cat: "adverbs",    ex: "其实我不喜欢咖啡。", exPy: "Qíshí wǒ bù xǐhuan kāfēi.", exEn: "Actually I don't like coffee." },
  { id: 483, hz: "其他",   py: "qítā",      en: "other",                          cat: "pronouns",   ex: "其他人都走了。", exPy: "Qítā rén dōu zǒu le.", exEn: "The others have all left." },
  { id: 484, hz: "奇怪",   py: "qíguài",    en: "strange, odd",                   cat: "adjectives", ex: "这件事很奇怪。", exPy: "Zhè jiàn shì hěn qíguài.", exEn: "This matter is very strange." },
  { id: 485, hz: "骑",     py: "qí",        en: "to ride (bike, horse)",          cat: "verbs",      ex: "我骑自行车上学。", exPy: "Wǒ qí zìxíngchē shàngxué.", exEn: "I ride a bike to school." },
  { id: 486, hz: "起飞",   py: "qǐfēi",     en: "to take off (plane)",            cat: "transport",  ex: "飞机九点起飞。", exPy: "Fēijī jiǔ diǎn qǐfēi.", exEn: "The plane takes off at nine." },
  { id: 487, hz: "起来",   py: "qǐlai",     en: "to get up; (starting an action)", cat: "verbs",     ex: "快起来，要迟到了！", exPy: "Kuài qǐlai, yào chídào le!", exEn: "Get up quickly, you'll be late!" },
  { id: 488, hz: "清楚",   py: "qīngchu",   en: "clear",                          cat: "adjectives", ex: "我听得很清楚。", exPy: "Wǒ tīng de hěn qīngchu.", exEn: "I hear it very clearly." },
  { id: 489, hz: "请假",   py: "qǐngjià",   en: "to ask for leave",               cat: "study",      ex: "我明天想请假。", exPy: "Wǒ míngtiān xiǎng qǐngjià.", exEn: "I'd like to take a day off tomorrow." },
  { id: 490, hz: "秋",     py: "qiū",       en: "autumn",                         cat: "time",       ex: "秋天很凉快。", exPy: "Qiūtiān hěn liángkuai.", exEn: "Autumn is cool." },
  { id: 491, hz: "裙子",   py: "qúnzi",     en: "skirt",                          cat: "objects",    ex: "她穿了一条红裙子。", exPy: "Tā chuān le yì tiáo hóng qúnzi.", exEn: "She is wearing a red skirt." },
  { id: 492, hz: "然后",   py: "ránhòu",    en: "then, afterwards",               cat: "adverbs",    ex: "先吃饭，然后看电影。", exPy: "Xiān chīfàn, ránhòu kàn diànyǐng.", exEn: "First eat, then watch a movie." },
  { id: 493, hz: "热情",   py: "rèqíng",    en: "warm, enthusiastic",             cat: "adjectives", ex: "中国人很热情。", exPy: "Zhōngguó rén hěn rèqíng.", exEn: "Chinese people are very warm-hearted." },
  { id: 494, hz: "认为",   py: "rènwéi",    en: "to think, to believe",           cat: "verbs",      ex: "我认为你是对的。", exPy: "Wǒ rènwéi nǐ shì duì de.", exEn: "I think you are right." },
  { id: 495, hz: "认真",   py: "rènzhēn",   en: "serious, earnest",               cat: "adjectives", ex: "他工作很认真。", exPy: "Tā gōngzuò hěn rènzhēn.", exEn: "He works very conscientiously." },
  { id: 496, hz: "容易",   py: "róngyì",    en: "easy",                           cat: "adjectives", ex: "这个题很容易。", exPy: "Zhège tí hěn róngyì.", exEn: "This question is easy." },
  { id: 497, hz: "如果",   py: "rúguǒ",     en: "if",                             cat: "adverbs",    ex: "如果下雨，我就不去。", exPy: "Rúguǒ xiàyǔ, wǒ jiù bú qù.", exEn: "If it rains, I won't go." },
  { id: 498, hz: "伞",     py: "sǎn",       en: "umbrella",                       cat: "objects",    ex: "别忘了带伞。", exPy: "Bié wàng le dài sǎn.", exEn: "Don't forget to bring an umbrella." },
  { id: 499, hz: "上网",   py: "shàngwǎng", en: "to go online",                   cat: "verbs",      ex: "我晚上上网看新闻。", exPy: "Wǒ wǎnshang shàngwǎng kàn xīnwén.", exEn: "In the evening I go online to read the news." },
  { id: 500, hz: "生气",   py: "shēngqì",   en: "to get angry",                   cat: "verbs",      ex: "别生气了。", exPy: "Bié shēngqì le.", exEn: "Don't be angry." },
  { id: 501, hz: "声音",   py: "shēngyīn",  en: "sound, voice",                   cat: "misc",       ex: "她的声音很好听。", exPy: "Tā de shēngyīn hěn hǎotīng.", exEn: "Her voice is very pleasant." },
  { id: 502, hz: "世界",   py: "shìjiè",    en: "world",                          cat: "places",     ex: "世界很大。", exPy: "Shìjiè hěn dà.", exEn: "The world is big." },
  { id: 503, hz: "试",     py: "shì",       en: "to try",                         cat: "verbs",      ex: "我可以试一下吗？", exPy: "Wǒ kěyǐ shì yíxià ma?", exEn: "May I try it?" },
  { id: 504, hz: "瘦",     py: "shòu",      en: "thin, slim",                     cat: "adjectives", ex: "她很瘦。", exPy: "Tā hěn shòu.", exEn: "She is very thin." },
  { id: 505, hz: "叔叔",   py: "shūshu",    en: "uncle (father's younger brother)", cat: "family",   ex: "叔叔送我一本书。", exPy: "Shūshu sòng wǒ yì běn shū.", exEn: "My uncle gave me a book." },
  { id: 506, hz: "舒服",   py: "shūfu",     en: "comfortable",                    cat: "adjectives", ex: "这个椅子很舒服。", exPy: "Zhège yǐzi hěn shūfu.", exEn: "This chair is very comfortable." },
  { id: 507, hz: "树",     py: "shù",       en: "tree",                           cat: "nature",     ex: "公园里有很多树。", exPy: "Gōngyuán lǐ yǒu hěn duō shù.", exEn: "There are many trees in the park." },
  { id: 508, hz: "数学",   py: "shùxué",    en: "mathematics",                    cat: "study",      ex: "我喜欢数学。", exPy: "Wǒ xǐhuan shùxué.", exEn: "I like math." },
  { id: 509, hz: "刷牙",   py: "shuāyá",    en: "to brush teeth",                 cat: "verbs",      ex: "我每天刷两次牙。", exPy: "Wǒ měi tiān shuā liǎng cì yá.", exEn: "I brush my teeth twice a day." },
  { id: 510, hz: "双",     py: "shuāng",    en: "pair (measure word)",            cat: "measure",    ex: "我买了一双鞋。", exPy: "Wǒ mǎi le yì shuāng xié.", exEn: "I bought a pair of shoes." },
  { id: 511, hz: "水平",   py: "shuǐpíng",  en: "level, standard",                cat: "misc",       ex: "他的汉语水平很高。", exPy: "Tā de Hànyǔ shuǐpíng hěn gāo.", exEn: "His Chinese level is very high." },
  { id: 512, hz: "司机",   py: "sījī",      en: "driver",                         cat: "people",     ex: "司机开得很快。", exPy: "Sījī kāi de hěn kuài.", exEn: "The driver drives very fast." },
  { id: 513, hz: "太阳",   py: "tàiyáng",   en: "sun",                            cat: "nature",     ex: "今天太阳很大。", exPy: "Jīntiān tàiyáng hěn dà.", exEn: "The sun is strong today." },
  { id: 514, hz: "特别",   py: "tèbié",     en: "special; especially",            cat: "adverbs",    ex: "今天特别热。", exPy: "Jīntiān tèbié rè.", exEn: "It's especially hot today." },
  { id: 515, hz: "疼",     py: "téng",      en: "to hurt, painful",               cat: "body",       ex: "我头疼。", exPy: "Wǒ tóu téng.", exEn: "I have a headache." },
  { id: 516, hz: "提高",   py: "tígāo",     en: "to improve, to raise",           cat: "verbs",      ex: "我想提高汉语水平。", exPy: "Wǒ xiǎng tígāo Hànyǔ shuǐpíng.", exEn: "I want to improve my Chinese." },
  { id: 517, hz: "体育",   py: "tǐyù",      en: "sports, physical education",     cat: "sports",     ex: "我喜欢体育课。", exPy: "Wǒ xǐhuan tǐyù kè.", exEn: "I like PE class." },
  { id: 518, hz: "甜",     py: "tián",      en: "sweet",                          cat: "adjectives", ex: "这个西瓜很甜。", exPy: "Zhège xīguā hěn tián.", exEn: "This watermelon is very sweet." },
  { id: 519, hz: "条",     py: "tiáo",      en: "(measure word for long, thin things)", cat: "measure", ex: "这条裙子很漂亮。", exPy: "Zhè tiáo qúnzi hěn piàoliang.", exEn: "This skirt is very pretty." },
  { id: 520, hz: "同事",   py: "tóngshì",   en: "colleague",                      cat: "people",     ex: "他是我的同事。", exPy: "Tā shì wǒ de tóngshì.", exEn: "He is my colleague." },
  { id: 521, hz: "同意",   py: "tóngyì",    en: "to agree",                       cat: "verbs",      ex: "我同意你的看法。", exPy: "Wǒ tóngyì nǐ de kànfǎ.", exEn: "I agree with your view." },
  { id: 522, hz: "头发",   py: "tóufa",     en: "hair",                           cat: "body",       ex: "她的头发很长。", exPy: "Tā de tóufa hěn cháng.", exEn: "Her hair is very long." },
  { id: 523, hz: "突然",   py: "tūrán",     en: "suddenly",                       cat: "adverbs",    ex: "突然下雨了。", exPy: "Tūrán xiàyǔ le.", exEn: "Suddenly it started to rain." },
  { id: 524, hz: "图书馆", py: "túshūguǎn", en: "library",                        cat: "places",     ex: "我在图书馆看书。", exPy: "Wǒ zài túshūguǎn kàn shū.", exEn: "I read in the library." },
  { id: 525, hz: "腿",     py: "tuǐ",       en: "leg",                            cat: "body",       ex: "我的腿很疼。", exPy: "Wǒ de tuǐ hěn téng.", exEn: "My leg hurts." },
  { id: 526, hz: "完成",   py: "wánchéng",  en: "to complete",                    cat: "verbs",      ex: "我完成了作业。", exPy: "Wǒ wánchéng le zuòyè.", exEn: "I finished my homework." },
  { id: 527, hz: "碗",     py: "wǎn",       en: "bowl",                           cat: "objects",    ex: "我要一碗米饭。", exPy: "Wǒ yào yì wǎn mǐfàn.", exEn: "I want a bowl of rice." },
  { id: 528, hz: "万",     py: "wàn",       en: "ten thousand",                   cat: "numbers",    ex: "这辆车十万块。", exPy: "Zhè liàng chē shí wàn kuài.", exEn: "This car costs 100,000 yuan." },
  { id: 529, hz: "忘记",   py: "wàngjì",    en: "to forget",                      cat: "verbs",      ex: "我忘记带钱了。", exPy: "Wǒ wàngjì dài qián le.", exEn: "I forgot to bring money." },
  { id: 530, hz: "为",     py: "wèi",       en: "for; because of",                cat: "particles",  ex: "我为你高兴。", exPy: "Wǒ wèi nǐ gāoxìng.", exEn: "I'm happy for you." },
  { id: 531, hz: "为了",   py: "wèile",     en: "in order to, for",               cat: "particles",  ex: "为了健康，我每天运动。", exPy: "Wèile jiànkāng, wǒ měi tiān yùndòng.", exEn: "For my health, I exercise every day." },
  { id: 532, hz: "位",     py: "wèi",       en: "(polite measure word for people)", cat: "measure",  ex: "这位是王老师。", exPy: "Zhè wèi shì Wáng lǎoshī.", exEn: "This is Teacher Wang." },
  { id: 533, hz: "文化",   py: "wénhuà",    en: "culture",                        cat: "misc",       ex: "我对中国文化很感兴趣。", exPy: "Wǒ duì Zhōngguó wénhuà hěn gǎn xìngqù.", exEn: "I'm very interested in Chinese culture." },
  { id: 534, hz: "西",     py: "xī",        en: "west",                           cat: "places",     ex: "太阳从西边落下。", exPy: "Tàiyáng cóng xībian luòxià.", exEn: "The sun sets in the west." },
  { id: 535, hz: "习惯",   py: "xíguàn",    en: "habit; to be used to",           cat: "misc",       ex: "我习惯早起。", exPy: "Wǒ xíguàn zǎo qǐ.", exEn: "I'm used to getting up early." },
  { id: 536, hz: "洗手间", py: "xǐshǒujiān", en: "restroom, toilet",              cat: "places",     ex: "洗手间在哪儿？", exPy: "Xǐshǒujiān zài nǎr?", exEn: "Where is the restroom?" },
  { id: 537, hz: "洗澡",   py: "xǐzǎo",     en: "to take a shower/bath",          cat: "verbs",      ex: "我晚上洗澡。", exPy: "Wǒ wǎnshang xǐzǎo.", exEn: "I shower in the evening." },
  { id: 538, hz: "夏",     py: "xià",       en: "summer",                         cat: "time",       ex: "夏天很热。", exPy: "Xiàtiān hěn rè.", exEn: "Summer is hot." },
  { id: 539, hz: "先",     py: "xiān",      en: "first, before",                  cat: "adverbs",    ex: "你先走吧。", exPy: "Nǐ xiān zǒu ba.", exEn: "You go first." },
  { id: 540, hz: "相信",   py: "xiāngxìn",  en: "to believe, to trust",           cat: "verbs",      ex: "我相信你。", exPy: "Wǒ xiāngxìn nǐ.", exEn: "I believe you." },
  { id: 541, hz: "香蕉",   py: "xiāngjiāo", en: "banana",                         cat: "food",       ex: "猴子喜欢吃香蕉。", exPy: "Hóuzi xǐhuan chī xiāngjiāo.", exEn: "Monkeys like eating bananas." },
  { id: 542, hz: "向",     py: "xiàng",     en: "towards, to",                    cat: "particles",  ex: "向右转。", exPy: "Xiàng yòu zhuǎn.", exEn: "Turn right." },
  { id: 543, hz: "像",     py: "xiàng",     en: "to resemble, to be like",        cat: "verbs",      ex: "她长得像妈妈。", exPy: "Tā zhǎng de xiàng māma.", exEn: "She looks like her mom." },
  { id: 544, hz: "小心",   py: "xiǎoxīn",   en: "to be careful",                  cat: "verbs",      ex: "小心，车来了！", exPy: "Xiǎoxīn, chē lái le!", exEn: "Careful, a car is coming!" },
  { id: 545, hz: "校长",   py: "xiàozhǎng", en: "school principal",               cat: "people",     ex: "校长在开会。", exPy: "Xiàozhǎng zài kāihuì.", exEn: "The principal is in a meeting." },
  { id: 546, hz: "新闻",   py: "xīnwén",    en: "news",                           cat: "misc",       ex: "我每天看新闻。", exPy: "Wǒ měi tiān kàn xīnwén.", exEn: "I watch the news every day." },
  { id: 547, hz: "新鲜",   py: "xīnxiān",   en: "fresh",                          cat: "adjectives", ex: "这些水果很新鲜。", exPy: "Zhèxiē shuǐguǒ hěn xīnxiān.", exEn: "These fruits are very fresh." },
  { id: 548, hz: "信用卡", py: "xìnyòngkǎ", en: "credit card",                    cat: "objects",    ex: "可以用信用卡吗？", exPy: "Kěyǐ yòng xìnyòngkǎ ma?", exEn: "Can I pay by credit card?" },
  { id: 549, hz: "行李箱", py: "xínglǐxiāng", en: "suitcase",                     cat: "objects",    ex: "我的行李箱很重。", exPy: "Wǒ de xínglǐxiāng hěn zhòng.", exEn: "My suitcase is very heavy." },
  { id: 550, hz: "熊猫",   py: "xióngmāo",  en: "panda",                          cat: "animals",    ex: "熊猫很可爱。", exPy: "Xióngmāo hěn kě'ài.", exEn: "Pandas are very cute." },
  { id: 551, hz: "需要",   py: "xūyào",     en: "to need",                        cat: "verbs",      ex: "你需要帮助吗？", exPy: "Nǐ xūyào bāngzhù ma?", exEn: "Do you need help?" },
  { id: 552, hz: "选择",   py: "xuǎnzé",    en: "to choose; choice",              cat: "verbs",      ex: "你可以选择一个。", exPy: "Nǐ kěyǐ xuǎnzé yí gè.", exEn: "You can choose one." },
  { id: 553, hz: "要求",   py: "yāoqiú",    en: "to require; requirement",        cat: "verbs",      ex: "老师要求我们每天练习。", exPy: "Lǎoshī yāoqiú wǒmen měi tiān liànxí.", exEn: "The teacher requires us to practice daily." },
  { id: 554, hz: "爷爷",   py: "yéye",      en: "grandfather (father's side)",    cat: "family",     ex: "爷爷喜欢喝茶。", exPy: "Yéye xǐhuan hē chá.", exEn: "Grandpa likes drinking tea." },
  { id: 555, hz: "一般",   py: "yìbān",     en: "general, ordinary; usually",     cat: "adverbs",    ex: "我一般七点起床。", exPy: "Wǒ yìbān qī diǎn qǐchuáng.", exEn: "I usually get up at seven." },
  { id: 556, hz: "一边",   py: "yìbiān",    en: "while (doing two things at once)", cat: "adverbs",  ex: "他一边吃饭一边看电视。", exPy: "Tā yìbiān chīfàn yìbiān kàn diànshì.", exEn: "He eats while watching TV." },
  { id: 557, hz: "一定",   py: "yídìng",    en: "certainly, must",                cat: "adverbs",    ex: "我一定来。", exPy: "Wǒ yídìng lái.", exEn: "I will certainly come." },
  { id: 558, hz: "一共",   py: "yígòng",    en: "altogether, in total",           cat: "adverbs",    ex: "一共多少钱？", exPy: "Yígòng duōshao qián?", exEn: "How much is it altogether?" },
  { id: 559, hz: "一会儿", py: "yíhuìr",    en: "a little while",                 cat: "time",       ex: "请等一会儿。", exPy: "Qǐng děng yíhuìr.", exEn: "Please wait a little while." },
  { id: 560, hz: "一样",   py: "yíyàng",    en: "the same",                       cat: "adjectives", ex: "我们的衣服一样。", exPy: "Wǒmen de yīfu yíyàng.", exEn: "Our clothes are the same." },
  { id: 561, hz: "一直",   py: "yìzhí",     en: "always, all along; straight",    cat: "adverbs",    ex: "一直往前走。", exPy: "Yìzhí wǎng qián zǒu.", exEn: "Keep going straight ahead." },
  { id: 562, hz: "以前",   py: "yǐqián",    en: "before, formerly",               cat: "time",       ex: "我以前住在上海。", exPy: "Wǒ yǐqián zhù zài Shànghǎi.", exEn: "I used to live in Shanghai." },
  { id: 563, hz: "音乐",   py: "yīnyuè",    en: "music",                          cat: "sports",     ex: "我喜欢听音乐。", exPy: "Wǒ xǐhuan tīng yīnyuè.", exEn: "I like listening to music." },
  { id: 564, hz: "银行",   py: "yínháng",   en: "bank",                           cat: "places",     ex: "我去银行取钱。", exPy: "Wǒ qù yínháng qǔ qián.", exEn: "I'm going to the bank to withdraw money." },
  { id: 565, hz: "饮料",   py: "yǐnliào",   en: "drink, beverage",                cat: "food",       ex: "你想喝什么饮料？", exPy: "Nǐ xiǎng hē shénme yǐnliào?", exEn: "What would you like to drink?" },
  { id: 566, hz: "应该",   py: "yīnggāi",   en: "should, ought to",               cat: "verbs",      ex: "你应该多休息。", exPy: "Nǐ yīnggāi duō xiūxi.", exEn: "You should rest more." },
  { id: 567, hz: "影响",   py: "yǐngxiǎng", en: "to influence; influence",        cat: "verbs",      ex: "天气影响我的心情。", exPy: "Tiānqì yǐngxiǎng wǒ de xīnqíng.", exEn: "The weather affects my mood." },
  { id: 568, hz: "用",     py: "yòng",      en: "to use",                         cat: "verbs",      ex: "我用手机看新闻。", exPy: "Wǒ yòng shǒujī kàn xīnwén.", exEn: "I read the news on my phone." },
  { id: 569, hz: "游戏",   py: "yóuxì",     en: "game",                           cat: "sports",     ex: "孩子们在玩游戏。", exPy: "Háizimen zài wán yóuxì.", exEn: "The children are playing a game." },
  { id: 570, hz: "有名",   py: "yǒumíng",   en: "famous",                         cat: "adjectives", ex: "他是有名的医生。", exPy: "Tā shì yǒumíng de yīshēng.", exEn: "He is a famous doctor." },
  { id: 571, hz: "又",     py: "yòu",       en: "again; both... and",             cat: "adverbs",    ex: "他又迟到了。", exPy: "Tā yòu chídào le.", exEn: "He was late again." },
  { id: 572, hz: "遇到",   py: "yùdào",     en: "to meet, to run into",           cat: "verbs",      ex: "我在路上遇到了老师。", exPy: "Wǒ zài lù shàng yùdào le lǎoshī.", exEn: "I ran into my teacher on the way." },
  { id: 573, hz: "元",     py: "yuán",      en: "yuan (currency unit)",           cat: "measure",    ex: "这本书二十元。", exPy: "Zhè běn shū èrshí yuán.", exEn: "This book costs 20 yuan." },
  { id: 574, hz: "愿意",   py: "yuànyì",    en: "to be willing",                  cat: "verbs",      ex: "我愿意帮你。", exPy: "Wǒ yuànyì bāng nǐ.", exEn: "I'm willing to help you." },
  { id: 575, hz: "月亮",   py: "yuèliang",  en: "moon",                           cat: "nature",     ex: "今晚的月亮很圆。", exPy: "Jīnwǎn de yuèliang hěn yuán.", exEn: "The moon is very round tonight." },
  { id: 576, hz: "越",     py: "yuè",       en: "the more... the more",           cat: "adverbs",    ex: "我越学越喜欢汉语。", exPy: "Wǒ yuè xué yuè xǐhuan Hànyǔ.", exEn: "The more I study Chinese, the more I like it." },
  { id: 577, hz: "站",     py: "zhàn",      en: "to stand; station, stop",        cat: "verbs",      ex: "下一站是北京站。", exPy: "Xià yí zhàn shì Běijīng zhàn.", exEn: "The next stop is Beijing Station." },
  { id: 578, hz: "张",     py: "zhāng",     en: "(measure word for flat objects)", cat: "measure",   ex: "我买了三张票。", exPy: "Wǒ mǎi le sān zhāng piào.", exEn: "I bought three tickets." },
  { id: 579, hz: "长",     py: "zhǎng",     en: "to grow",                        cat: "verbs",      ex: "孩子长得很快。", exPy: "Háizi zhǎng de hěn kuài.", exEn: "Children grow very fast." },
  { id: 580, hz: "着急",   py: "zháojí",    en: "anxious, in a hurry",            cat: "adjectives", ex: "别着急，还有时间。", exPy: "Bié zháojí, hái yǒu shíjiān.", exEn: "Don't worry, there's still time." },
  { id: 581, hz: "照顾",   py: "zhàogu",    en: "to take care of",                cat: "verbs",      ex: "她照顾生病的妈妈。", exPy: "Tā zhàogu shēngbìng de māma.", exEn: "She takes care of her sick mother." },
  { id: 582, hz: "照片",   py: "zhàopiàn",  en: "photo",                          cat: "objects",    ex: "这是我们的照片。", exPy: "Zhè shì wǒmen de zhàopiàn.", exEn: "This is our photo." },
  { id: 583, hz: "照相机", py: "zhàoxiàngjī", en: "camera",                       cat: "objects",    ex: "我带了照相机。", exPy: "Wǒ dài le zhàoxiàngjī.", exEn: "I brought a camera." },
  { id: 584, hz: "只",     py: "zhī",       en: "(measure word for animals); only (zhǐ)", cat: "measure", ex: "我有一只狗。", exPy: "Wǒ yǒu yì zhī gǒu.", exEn: "I have a dog." },
  { id: 585, hz: "只有",   py: "zhǐyǒu",    en: "only; only if",                  cat: "adverbs",    ex: "只有他知道答案。", exPy: "Zhǐyǒu tā zhīdao dá'àn.", exEn: "Only he knows the answer." },
  { id: 586, hz: "才",     py: "cái",       en: "only then; not until; just",     cat: "adverbs",    ex: "他十点才来。", exPy: "Tā shí diǎn cái lái.", exEn: "He didn't come until ten." },
  { id: 587, hz: "中间",   py: "zhōngjiān", en: "middle, between",                cat: "places",     ex: "我坐在中间。", exPy: "Wǒ zuò zài zhōngjiān.", exEn: "I sit in the middle." },
  { id: 588, hz: "中文",   py: "Zhōngwén",  en: "Chinese (language)",             cat: "study",      ex: "你的中文很好。", exPy: "Nǐ de Zhōngwén hěn hǎo.", exEn: "Your Chinese is very good." },
  { id: 589, hz: "终于",   py: "zhōngyú",   en: "finally, at last",               cat: "adverbs",    ex: "我终于到了！", exPy: "Wǒ zhōngyú dào le!", exEn: "I finally arrived!" },
  { id: 590, hz: "种",     py: "zhǒng",     en: "kind, type (measure word)",      cat: "measure",    ex: "这种水果很甜。", exPy: "Zhè zhǒng shuǐguǒ hěn tián.", exEn: "This kind of fruit is very sweet." },
  { id: 591, hz: "重要",   py: "zhòngyào",  en: "important",                      cat: "adjectives", ex: "这个会议很重要。", exPy: "Zhège huìyì hěn zhòngyào.", exEn: "This meeting is very important." },
  { id: 592, hz: "周末",   py: "zhōumò",    en: "weekend",                        cat: "time",       ex: "周末你做什么？", exPy: "Zhōumò nǐ zuò shénme?", exEn: "What do you do on the weekend?" },
  { id: 593, hz: "主要",   py: "zhǔyào",    en: "main, mainly",                   cat: "adjectives", ex: "我主要学习汉语。", exPy: "Wǒ zhǔyào xuéxí Hànyǔ.", exEn: "I mainly study Chinese." },
  { id: 594, hz: "注意",   py: "zhùyì",     en: "to pay attention to",            cat: "verbs",      ex: "请注意安全。", exPy: "Qǐng zhùyì ānquán.", exEn: "Please pay attention to safety." },
  { id: 595, hz: "自己",   py: "zìjǐ",      en: "oneself",                        cat: "pronouns",   ex: "我自己做饭。", exPy: "Wǒ zìjǐ zuòfàn.", exEn: "I cook by myself." },
  { id: 596, hz: "自行车", py: "zìxíngchē", en: "bicycle",                        cat: "transport",  ex: "我骑自行车去上班。", exPy: "Wǒ qí zìxíngchē qù shàngbān.", exEn: "I ride a bike to work." },
  { id: 597, hz: "总是",   py: "zǒngshì",   en: "always",                         cat: "adverbs",    ex: "他总是很忙。", exPy: "Tā zǒngshì hěn máng.", exEn: "He is always busy." },
  { id: 598, hz: "嘴",     py: "zuǐ",       en: "mouth",                          cat: "body",       ex: "张开嘴。", exPy: "Zhāngkāi zuǐ.", exEn: "Open your mouth." },
  { id: 599, hz: "最后",   py: "zuìhòu",    en: "last, finally",                  cat: "time",       ex: "最后他同意了。", exPy: "Zuìhòu tā tóngyì le.", exEn: "In the end he agreed." },
  { id: 600, hz: "最近",   py: "zuìjìn",    en: "recently",                       cat: "time",       ex: "最近你怎么样？", exPy: "Zuìjìn nǐ zěnmeyàng?", exEn: "How have you been recently?" },
  { id: 601, hz: "作业",   py: "zuòyè",     en: "homework",                       cat: "study",      ex: "我在做作业。", exPy: "Wǒ zài zuò zuòyè.", exEn: "I'm doing my homework." }
];
